// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetBikeCurLocationResponse.proto

package com.yzh.rfidbike.app.response;

public final class GetBikeCurLocationResponse {
  private GetBikeCurLocationResponse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetBikeCurLocationResponseMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetBikeCurLocationResponseMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    boolean hasErrorMsg();
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    ErrorMessageResponse.ErrorMessage getErrorMsg();
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder();

    /**
     * <code>repeated .LocationMessage locations = 2;</code>
     */
    java.util.List<Location.LocationMessage>
        getLocationsList();
    /**
     * <code>repeated .LocationMessage locations = 2;</code>
     */
    Location.LocationMessage getLocations(int index);
    /**
     * <code>repeated .LocationMessage locations = 2;</code>
     */
    int getLocationsCount();
    /**
     * <code>repeated .LocationMessage locations = 2;</code>
     */
    java.util.List<? extends Location.LocationMessageOrBuilder>
        getLocationsOrBuilderList();
    /**
     * <code>repeated .LocationMessage locations = 2;</code>
     */
    Location.LocationMessageOrBuilder getLocationsOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code GetBikeCurLocationResponseMessage}
   */
  public  static final class GetBikeCurLocationResponseMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetBikeCurLocationResponseMessage)
      GetBikeCurLocationResponseMessageOrBuilder {
    // Use GetBikeCurLocationResponseMessage.newBuilder() to construct.
    private GetBikeCurLocationResponseMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetBikeCurLocationResponseMessage() {
      locations_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetBikeCurLocationResponseMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              ErrorMessageResponse.ErrorMessage.Builder subBuilder = null;
              if (errorMsg_ != null) {
                subBuilder = errorMsg_.toBuilder();
              }
              errorMsg_ = input.readMessage(ErrorMessageResponse.ErrorMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(errorMsg_);
                errorMsg_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                locations_ = new java.util.ArrayList<Location.LocationMessage>();
                mutable_bitField0_ |= 0x00000002;
              }
              locations_.add(
                  input.readMessage(Location.LocationMessage.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          locations_ = java.util.Collections.unmodifiableList(locations_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GetBikeCurLocationResponse.internal_static_GetBikeCurLocationResponseMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GetBikeCurLocationResponse.internal_static_GetBikeCurLocationResponseMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GetBikeCurLocationResponseMessage.class, Builder.class);
    }

    private int bitField0_;
    public static final int ERRORMSG_FIELD_NUMBER = 1;
    private ErrorMessageResponse.ErrorMessage errorMsg_;
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public boolean hasErrorMsg() {
      return errorMsg_ != null;
    }
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public ErrorMessageResponse.ErrorMessage getErrorMsg() {
      return errorMsg_ == null ? ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
    }
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder() {
      return getErrorMsg();
    }

    public static final int LOCATIONS_FIELD_NUMBER = 2;
    private java.util.List<Location.LocationMessage> locations_;
    /**
     * <code>repeated .LocationMessage locations = 2;</code>
     */
    public java.util.List<Location.LocationMessage> getLocationsList() {
      return locations_;
    }
    /**
     * <code>repeated .LocationMessage locations = 2;</code>
     */
    public java.util.List<? extends Location.LocationMessageOrBuilder>
        getLocationsOrBuilderList() {
      return locations_;
    }
    /**
     * <code>repeated .LocationMessage locations = 2;</code>
     */
    public int getLocationsCount() {
      return locations_.size();
    }
    /**
     * <code>repeated .LocationMessage locations = 2;</code>
     */
    public Location.LocationMessage getLocations(int index) {
      return locations_.get(index);
    }
    /**
     * <code>repeated .LocationMessage locations = 2;</code>
     */
    public Location.LocationMessageOrBuilder getLocationsOrBuilder(
        int index) {
      return locations_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (errorMsg_ != null) {
        output.writeMessage(1, getErrorMsg());
      }
      for (int i = 0; i < locations_.size(); i++) {
        output.writeMessage(2, locations_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (errorMsg_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getErrorMsg());
      }
      for (int i = 0; i < locations_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, locations_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GetBikeCurLocationResponseMessage)) {
        return super.equals(obj);
      }
      GetBikeCurLocationResponseMessage other = (GetBikeCurLocationResponseMessage) obj;

      boolean result = true;
      result = result && (hasErrorMsg() == other.hasErrorMsg());
      if (hasErrorMsg()) {
        result = result && getErrorMsg()
            .equals(other.getErrorMsg());
      }
      result = result && getLocationsList()
          .equals(other.getLocationsList());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasErrorMsg()) {
        hash = (37 * hash) + ERRORMSG_FIELD_NUMBER;
        hash = (53 * hash) + getErrorMsg().hashCode();
      }
      if (getLocationsCount() > 0) {
        hash = (37 * hash) + LOCATIONS_FIELD_NUMBER;
        hash = (53 * hash) + getLocationsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GetBikeCurLocationResponseMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GetBikeCurLocationResponseMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GetBikeCurLocationResponseMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GetBikeCurLocationResponseMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GetBikeCurLocationResponseMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GetBikeCurLocationResponseMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GetBikeCurLocationResponseMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GetBikeCurLocationResponseMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GetBikeCurLocationResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GetBikeCurLocationResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GetBikeCurLocationResponseMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetBikeCurLocationResponseMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetBikeCurLocationResponseMessage)
        GetBikeCurLocationResponseMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GetBikeCurLocationResponse.internal_static_GetBikeCurLocationResponseMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GetBikeCurLocationResponse.internal_static_GetBikeCurLocationResponseMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GetBikeCurLocationResponseMessage.class, Builder.class);
      }

      // Construct using com.yzh.rfidbike.app.response.GetBikeCurLocationResponse.GetBikeCurLocationResponseMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getLocationsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (errorMsgBuilder_ == null) {
          errorMsg_ = null;
        } else {
          errorMsg_ = null;
          errorMsgBuilder_ = null;
        }
        if (locationsBuilder_ == null) {
          locations_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          locationsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GetBikeCurLocationResponse.internal_static_GetBikeCurLocationResponseMessage_descriptor;
      }

      public GetBikeCurLocationResponseMessage getDefaultInstanceForType() {
        return GetBikeCurLocationResponseMessage.getDefaultInstance();
      }

      public GetBikeCurLocationResponseMessage build() {
        GetBikeCurLocationResponseMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public GetBikeCurLocationResponseMessage buildPartial() {
        GetBikeCurLocationResponseMessage result = new GetBikeCurLocationResponseMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (errorMsgBuilder_ == null) {
          result.errorMsg_ = errorMsg_;
        } else {
          result.errorMsg_ = errorMsgBuilder_.build();
        }
        if (locationsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            locations_ = java.util.Collections.unmodifiableList(locations_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.locations_ = locations_;
        } else {
          result.locations_ = locationsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GetBikeCurLocationResponseMessage) {
          return mergeFrom((GetBikeCurLocationResponseMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GetBikeCurLocationResponseMessage other) {
        if (other == GetBikeCurLocationResponseMessage.getDefaultInstance()) return this;
        if (other.hasErrorMsg()) {
          mergeErrorMsg(other.getErrorMsg());
        }
        if (locationsBuilder_ == null) {
          if (!other.locations_.isEmpty()) {
            if (locations_.isEmpty()) {
              locations_ = other.locations_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureLocationsIsMutable();
              locations_.addAll(other.locations_);
            }
            onChanged();
          }
        } else {
          if (!other.locations_.isEmpty()) {
            if (locationsBuilder_.isEmpty()) {
              locationsBuilder_.dispose();
              locationsBuilder_ = null;
              locations_ = other.locations_;
              bitField0_ = (bitField0_ & ~0x00000002);
              locationsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getLocationsFieldBuilder() : null;
            } else {
              locationsBuilder_.addAllMessages(other.locations_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GetBikeCurLocationResponseMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GetBikeCurLocationResponseMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private ErrorMessageResponse.ErrorMessage errorMsg_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          ErrorMessageResponse.ErrorMessage, ErrorMessageResponse.ErrorMessage.Builder, ErrorMessageResponse.ErrorMessageOrBuilder> errorMsgBuilder_;
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public boolean hasErrorMsg() {
        return errorMsgBuilder_ != null || errorMsg_ != null;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public ErrorMessageResponse.ErrorMessage getErrorMsg() {
        if (errorMsgBuilder_ == null) {
          return errorMsg_ == null ? ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
        } else {
          return errorMsgBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder setErrorMsg(ErrorMessageResponse.ErrorMessage value) {
        if (errorMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          errorMsg_ = value;
          onChanged();
        } else {
          errorMsgBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder setErrorMsg(
          ErrorMessageResponse.ErrorMessage.Builder builderForValue) {
        if (errorMsgBuilder_ == null) {
          errorMsg_ = builderForValue.build();
          onChanged();
        } else {
          errorMsgBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder mergeErrorMsg(ErrorMessageResponse.ErrorMessage value) {
        if (errorMsgBuilder_ == null) {
          if (errorMsg_ != null) {
            errorMsg_ =
              ErrorMessageResponse.ErrorMessage.newBuilder(errorMsg_).mergeFrom(value).buildPartial();
          } else {
            errorMsg_ = value;
          }
          onChanged();
        } else {
          errorMsgBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder clearErrorMsg() {
        if (errorMsgBuilder_ == null) {
          errorMsg_ = null;
          onChanged();
        } else {
          errorMsg_ = null;
          errorMsgBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public ErrorMessageResponse.ErrorMessage.Builder getErrorMsgBuilder() {
        
        onChanged();
        return getErrorMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder() {
        if (errorMsgBuilder_ != null) {
          return errorMsgBuilder_.getMessageOrBuilder();
        } else {
          return errorMsg_ == null ?
              ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
        }
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ErrorMessageResponse.ErrorMessage, ErrorMessageResponse.ErrorMessage.Builder, ErrorMessageResponse.ErrorMessageOrBuilder>
          getErrorMsgFieldBuilder() {
        if (errorMsgBuilder_ == null) {
          errorMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ErrorMessageResponse.ErrorMessage, ErrorMessageResponse.ErrorMessage.Builder, ErrorMessageResponse.ErrorMessageOrBuilder>(
                  getErrorMsg(),
                  getParentForChildren(),
                  isClean());
          errorMsg_ = null;
        }
        return errorMsgBuilder_;
      }

      private java.util.List<Location.LocationMessage> locations_ =
        java.util.Collections.emptyList();
      private void ensureLocationsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          locations_ = new java.util.ArrayList<Location.LocationMessage>(locations_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Location.LocationMessage, Location.LocationMessage.Builder, Location.LocationMessageOrBuilder> locationsBuilder_;

      /**
       * <code>repeated .LocationMessage locations = 2;</code>
       */
      public java.util.List<Location.LocationMessage> getLocationsList() {
        if (locationsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(locations_);
        } else {
          return locationsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .LocationMessage locations = 2;</code>
       */
      public int getLocationsCount() {
        if (locationsBuilder_ == null) {
          return locations_.size();
        } else {
          return locationsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .LocationMessage locations = 2;</code>
       */
      public Location.LocationMessage getLocations(int index) {
        if (locationsBuilder_ == null) {
          return locations_.get(index);
        } else {
          return locationsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .LocationMessage locations = 2;</code>
       */
      public Builder setLocations(
          int index, Location.LocationMessage value) {
        if (locationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLocationsIsMutable();
          locations_.set(index, value);
          onChanged();
        } else {
          locationsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .LocationMessage locations = 2;</code>
       */
      public Builder setLocations(
          int index, Location.LocationMessage.Builder builderForValue) {
        if (locationsBuilder_ == null) {
          ensureLocationsIsMutable();
          locations_.set(index, builderForValue.build());
          onChanged();
        } else {
          locationsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .LocationMessage locations = 2;</code>
       */
      public Builder addLocations(Location.LocationMessage value) {
        if (locationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLocationsIsMutable();
          locations_.add(value);
          onChanged();
        } else {
          locationsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .LocationMessage locations = 2;</code>
       */
      public Builder addLocations(
          int index, Location.LocationMessage value) {
        if (locationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLocationsIsMutable();
          locations_.add(index, value);
          onChanged();
        } else {
          locationsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .LocationMessage locations = 2;</code>
       */
      public Builder addLocations(
          Location.LocationMessage.Builder builderForValue) {
        if (locationsBuilder_ == null) {
          ensureLocationsIsMutable();
          locations_.add(builderForValue.build());
          onChanged();
        } else {
          locationsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .LocationMessage locations = 2;</code>
       */
      public Builder addLocations(
          int index, Location.LocationMessage.Builder builderForValue) {
        if (locationsBuilder_ == null) {
          ensureLocationsIsMutable();
          locations_.add(index, builderForValue.build());
          onChanged();
        } else {
          locationsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .LocationMessage locations = 2;</code>
       */
      public Builder addAllLocations(
          Iterable<? extends Location.LocationMessage> values) {
        if (locationsBuilder_ == null) {
          ensureLocationsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, locations_);
          onChanged();
        } else {
          locationsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .LocationMessage locations = 2;</code>
       */
      public Builder clearLocations() {
        if (locationsBuilder_ == null) {
          locations_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          locationsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .LocationMessage locations = 2;</code>
       */
      public Builder removeLocations(int index) {
        if (locationsBuilder_ == null) {
          ensureLocationsIsMutable();
          locations_.remove(index);
          onChanged();
        } else {
          locationsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .LocationMessage locations = 2;</code>
       */
      public Location.LocationMessage.Builder getLocationsBuilder(
          int index) {
        return getLocationsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .LocationMessage locations = 2;</code>
       */
      public Location.LocationMessageOrBuilder getLocationsOrBuilder(
          int index) {
        if (locationsBuilder_ == null) {
          return locations_.get(index);  } else {
          return locationsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .LocationMessage locations = 2;</code>
       */
      public java.util.List<? extends Location.LocationMessageOrBuilder>
           getLocationsOrBuilderList() {
        if (locationsBuilder_ != null) {
          return locationsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(locations_);
        }
      }
      /**
       * <code>repeated .LocationMessage locations = 2;</code>
       */
      public Location.LocationMessage.Builder addLocationsBuilder() {
        return getLocationsFieldBuilder().addBuilder(
            Location.LocationMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .LocationMessage locations = 2;</code>
       */
      public Location.LocationMessage.Builder addLocationsBuilder(
          int index) {
        return getLocationsFieldBuilder().addBuilder(
            index, Location.LocationMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .LocationMessage locations = 2;</code>
       */
      public java.util.List<Location.LocationMessage.Builder>
           getLocationsBuilderList() {
        return getLocationsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Location.LocationMessage, Location.LocationMessage.Builder, Location.LocationMessageOrBuilder>
          getLocationsFieldBuilder() {
        if (locationsBuilder_ == null) {
          locationsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Location.LocationMessage, Location.LocationMessage.Builder, Location.LocationMessageOrBuilder>(
                  locations_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          locations_ = null;
        }
        return locationsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:GetBikeCurLocationResponseMessage)
    }

    // @@protoc_insertion_point(class_scope:GetBikeCurLocationResponseMessage)
    private static final GetBikeCurLocationResponseMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GetBikeCurLocationResponseMessage();
    }

    public static GetBikeCurLocationResponseMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetBikeCurLocationResponseMessage>
        PARSER = new com.google.protobuf.AbstractParser<GetBikeCurLocationResponseMessage>() {
      public GetBikeCurLocationResponseMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetBikeCurLocationResponseMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetBikeCurLocationResponseMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<GetBikeCurLocationResponseMessage> getParserForType() {
      return PARSER;
    }

    public GetBikeCurLocationResponseMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetBikeCurLocationResponseMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetBikeCurLocationResponseMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n GetBikeCurLocationResponse.proto\032\032Erro" +
      "rMessageResponse.proto\032\016Location.proto\"i" +
      "\n!GetBikeCurLocationResponseMessage\022\037\n\010e" +
      "rrorMsg\030\001 \001(\0132\r.ErrorMessage\022#\n\tlocation" +
      "s\030\002 \003(\0132\020.LocationMessageB;\n\035com.yzh.rfi" +
      "dbike.app.responseB\032GetBikeCurLocationRe" +
      "sponseb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ErrorMessageResponse.getDescriptor(),
          Location.getDescriptor(),
        }, assigner);
    internal_static_GetBikeCurLocationResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetBikeCurLocationResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetBikeCurLocationResponseMessage_descriptor,
        new String[] { "ErrorMsg", "Locations", });
    ErrorMessageResponse.getDescriptor();
    Location.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
