// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetBikeInsurancePayoutResponse.proto

package com.yzh.rfidbike.app.response;

public final class GetBikeInsurancePayoutResponse {
  private GetBikeInsurancePayoutResponse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetBikeInsurancePayoutResponseMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetBikeInsurancePayoutResponseMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    boolean hasErrorMsg();
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    ErrorMessageResponse.ErrorMessage getErrorMsg();
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder();

    /**
     * <code>repeated .BikeInsurancePayoutMessage bikeInsurancePayoutMessage = 2;</code>
     */
    java.util.List<BikeInsurancePayout.BikeInsurancePayoutMessage>
        getBikeInsurancePayoutMessageList();
    /**
     * <code>repeated .BikeInsurancePayoutMessage bikeInsurancePayoutMessage = 2;</code>
     */
    BikeInsurancePayout.BikeInsurancePayoutMessage getBikeInsurancePayoutMessage(int index);
    /**
     * <code>repeated .BikeInsurancePayoutMessage bikeInsurancePayoutMessage = 2;</code>
     */
    int getBikeInsurancePayoutMessageCount();
    /**
     * <code>repeated .BikeInsurancePayoutMessage bikeInsurancePayoutMessage = 2;</code>
     */
    java.util.List<? extends BikeInsurancePayout.BikeInsurancePayoutMessageOrBuilder>
        getBikeInsurancePayoutMessageOrBuilderList();
    /**
     * <code>repeated .BikeInsurancePayoutMessage bikeInsurancePayoutMessage = 2;</code>
     */
    BikeInsurancePayout.BikeInsurancePayoutMessageOrBuilder getBikeInsurancePayoutMessageOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code GetBikeInsurancePayoutResponseMessage}
   */
  public  static final class GetBikeInsurancePayoutResponseMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetBikeInsurancePayoutResponseMessage)
      GetBikeInsurancePayoutResponseMessageOrBuilder {
    // Use GetBikeInsurancePayoutResponseMessage.newBuilder() to construct.
    private GetBikeInsurancePayoutResponseMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetBikeInsurancePayoutResponseMessage() {
      bikeInsurancePayoutMessage_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetBikeInsurancePayoutResponseMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              ErrorMessageResponse.ErrorMessage.Builder subBuilder = null;
              if (errorMsg_ != null) {
                subBuilder = errorMsg_.toBuilder();
              }
              errorMsg_ = input.readMessage(ErrorMessageResponse.ErrorMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(errorMsg_);
                errorMsg_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                bikeInsurancePayoutMessage_ = new java.util.ArrayList<BikeInsurancePayout.BikeInsurancePayoutMessage>();
                mutable_bitField0_ |= 0x00000002;
              }
              bikeInsurancePayoutMessage_.add(
                  input.readMessage(BikeInsurancePayout.BikeInsurancePayoutMessage.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          bikeInsurancePayoutMessage_ = java.util.Collections.unmodifiableList(bikeInsurancePayoutMessage_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GetBikeInsurancePayoutResponse.internal_static_GetBikeInsurancePayoutResponseMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GetBikeInsurancePayoutResponse.internal_static_GetBikeInsurancePayoutResponseMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GetBikeInsurancePayoutResponseMessage.class, Builder.class);
    }

    private int bitField0_;
    public static final int ERRORMSG_FIELD_NUMBER = 1;
    private ErrorMessageResponse.ErrorMessage errorMsg_;
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public boolean hasErrorMsg() {
      return errorMsg_ != null;
    }
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public ErrorMessageResponse.ErrorMessage getErrorMsg() {
      return errorMsg_ == null ? ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
    }
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder() {
      return getErrorMsg();
    }

    public static final int BIKEINSURANCEPAYOUTMESSAGE_FIELD_NUMBER = 2;
    private java.util.List<BikeInsurancePayout.BikeInsurancePayoutMessage> bikeInsurancePayoutMessage_;
    /**
     * <code>repeated .BikeInsurancePayoutMessage bikeInsurancePayoutMessage = 2;</code>
     */
    public java.util.List<BikeInsurancePayout.BikeInsurancePayoutMessage> getBikeInsurancePayoutMessageList() {
      return bikeInsurancePayoutMessage_;
    }
    /**
     * <code>repeated .BikeInsurancePayoutMessage bikeInsurancePayoutMessage = 2;</code>
     */
    public java.util.List<? extends BikeInsurancePayout.BikeInsurancePayoutMessageOrBuilder>
        getBikeInsurancePayoutMessageOrBuilderList() {
      return bikeInsurancePayoutMessage_;
    }
    /**
     * <code>repeated .BikeInsurancePayoutMessage bikeInsurancePayoutMessage = 2;</code>
     */
    public int getBikeInsurancePayoutMessageCount() {
      return bikeInsurancePayoutMessage_.size();
    }
    /**
     * <code>repeated .BikeInsurancePayoutMessage bikeInsurancePayoutMessage = 2;</code>
     */
    public BikeInsurancePayout.BikeInsurancePayoutMessage getBikeInsurancePayoutMessage(int index) {
      return bikeInsurancePayoutMessage_.get(index);
    }
    /**
     * <code>repeated .BikeInsurancePayoutMessage bikeInsurancePayoutMessage = 2;</code>
     */
    public BikeInsurancePayout.BikeInsurancePayoutMessageOrBuilder getBikeInsurancePayoutMessageOrBuilder(
        int index) {
      return bikeInsurancePayoutMessage_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (errorMsg_ != null) {
        output.writeMessage(1, getErrorMsg());
      }
      for (int i = 0; i < bikeInsurancePayoutMessage_.size(); i++) {
        output.writeMessage(2, bikeInsurancePayoutMessage_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (errorMsg_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getErrorMsg());
      }
      for (int i = 0; i < bikeInsurancePayoutMessage_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, bikeInsurancePayoutMessage_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GetBikeInsurancePayoutResponseMessage)) {
        return super.equals(obj);
      }
      GetBikeInsurancePayoutResponseMessage other = (GetBikeInsurancePayoutResponseMessage) obj;

      boolean result = true;
      result = result && (hasErrorMsg() == other.hasErrorMsg());
      if (hasErrorMsg()) {
        result = result && getErrorMsg()
            .equals(other.getErrorMsg());
      }
      result = result && getBikeInsurancePayoutMessageList()
          .equals(other.getBikeInsurancePayoutMessageList());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasErrorMsg()) {
        hash = (37 * hash) + ERRORMSG_FIELD_NUMBER;
        hash = (53 * hash) + getErrorMsg().hashCode();
      }
      if (getBikeInsurancePayoutMessageCount() > 0) {
        hash = (37 * hash) + BIKEINSURANCEPAYOUTMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getBikeInsurancePayoutMessageList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GetBikeInsurancePayoutResponseMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GetBikeInsurancePayoutResponseMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GetBikeInsurancePayoutResponseMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GetBikeInsurancePayoutResponseMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GetBikeInsurancePayoutResponseMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GetBikeInsurancePayoutResponseMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GetBikeInsurancePayoutResponseMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GetBikeInsurancePayoutResponseMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GetBikeInsurancePayoutResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GetBikeInsurancePayoutResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GetBikeInsurancePayoutResponseMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetBikeInsurancePayoutResponseMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetBikeInsurancePayoutResponseMessage)
        GetBikeInsurancePayoutResponseMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GetBikeInsurancePayoutResponse.internal_static_GetBikeInsurancePayoutResponseMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GetBikeInsurancePayoutResponse.internal_static_GetBikeInsurancePayoutResponseMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GetBikeInsurancePayoutResponseMessage.class, Builder.class);
      }

      // Construct using com.yzh.rfidbike.app.response.GetBikeInsurancePayoutResponse.GetBikeInsurancePayoutResponseMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getBikeInsurancePayoutMessageFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (errorMsgBuilder_ == null) {
          errorMsg_ = null;
        } else {
          errorMsg_ = null;
          errorMsgBuilder_ = null;
        }
        if (bikeInsurancePayoutMessageBuilder_ == null) {
          bikeInsurancePayoutMessage_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          bikeInsurancePayoutMessageBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GetBikeInsurancePayoutResponse.internal_static_GetBikeInsurancePayoutResponseMessage_descriptor;
      }

      public GetBikeInsurancePayoutResponseMessage getDefaultInstanceForType() {
        return GetBikeInsurancePayoutResponseMessage.getDefaultInstance();
      }

      public GetBikeInsurancePayoutResponseMessage build() {
        GetBikeInsurancePayoutResponseMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public GetBikeInsurancePayoutResponseMessage buildPartial() {
        GetBikeInsurancePayoutResponseMessage result = new GetBikeInsurancePayoutResponseMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (errorMsgBuilder_ == null) {
          result.errorMsg_ = errorMsg_;
        } else {
          result.errorMsg_ = errorMsgBuilder_.build();
        }
        if (bikeInsurancePayoutMessageBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            bikeInsurancePayoutMessage_ = java.util.Collections.unmodifiableList(bikeInsurancePayoutMessage_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.bikeInsurancePayoutMessage_ = bikeInsurancePayoutMessage_;
        } else {
          result.bikeInsurancePayoutMessage_ = bikeInsurancePayoutMessageBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GetBikeInsurancePayoutResponseMessage) {
          return mergeFrom((GetBikeInsurancePayoutResponseMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GetBikeInsurancePayoutResponseMessage other) {
        if (other == GetBikeInsurancePayoutResponseMessage.getDefaultInstance()) return this;
        if (other.hasErrorMsg()) {
          mergeErrorMsg(other.getErrorMsg());
        }
        if (bikeInsurancePayoutMessageBuilder_ == null) {
          if (!other.bikeInsurancePayoutMessage_.isEmpty()) {
            if (bikeInsurancePayoutMessage_.isEmpty()) {
              bikeInsurancePayoutMessage_ = other.bikeInsurancePayoutMessage_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureBikeInsurancePayoutMessageIsMutable();
              bikeInsurancePayoutMessage_.addAll(other.bikeInsurancePayoutMessage_);
            }
            onChanged();
          }
        } else {
          if (!other.bikeInsurancePayoutMessage_.isEmpty()) {
            if (bikeInsurancePayoutMessageBuilder_.isEmpty()) {
              bikeInsurancePayoutMessageBuilder_.dispose();
              bikeInsurancePayoutMessageBuilder_ = null;
              bikeInsurancePayoutMessage_ = other.bikeInsurancePayoutMessage_;
              bitField0_ = (bitField0_ & ~0x00000002);
              bikeInsurancePayoutMessageBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getBikeInsurancePayoutMessageFieldBuilder() : null;
            } else {
              bikeInsurancePayoutMessageBuilder_.addAllMessages(other.bikeInsurancePayoutMessage_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GetBikeInsurancePayoutResponseMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GetBikeInsurancePayoutResponseMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private ErrorMessageResponse.ErrorMessage errorMsg_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          ErrorMessageResponse.ErrorMessage, ErrorMessageResponse.ErrorMessage.Builder, ErrorMessageResponse.ErrorMessageOrBuilder> errorMsgBuilder_;
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public boolean hasErrorMsg() {
        return errorMsgBuilder_ != null || errorMsg_ != null;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public ErrorMessageResponse.ErrorMessage getErrorMsg() {
        if (errorMsgBuilder_ == null) {
          return errorMsg_ == null ? ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
        } else {
          return errorMsgBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder setErrorMsg(ErrorMessageResponse.ErrorMessage value) {
        if (errorMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          errorMsg_ = value;
          onChanged();
        } else {
          errorMsgBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder setErrorMsg(
          ErrorMessageResponse.ErrorMessage.Builder builderForValue) {
        if (errorMsgBuilder_ == null) {
          errorMsg_ = builderForValue.build();
          onChanged();
        } else {
          errorMsgBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder mergeErrorMsg(ErrorMessageResponse.ErrorMessage value) {
        if (errorMsgBuilder_ == null) {
          if (errorMsg_ != null) {
            errorMsg_ =
              ErrorMessageResponse.ErrorMessage.newBuilder(errorMsg_).mergeFrom(value).buildPartial();
          } else {
            errorMsg_ = value;
          }
          onChanged();
        } else {
          errorMsgBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder clearErrorMsg() {
        if (errorMsgBuilder_ == null) {
          errorMsg_ = null;
          onChanged();
        } else {
          errorMsg_ = null;
          errorMsgBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public ErrorMessageResponse.ErrorMessage.Builder getErrorMsgBuilder() {
        
        onChanged();
        return getErrorMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder() {
        if (errorMsgBuilder_ != null) {
          return errorMsgBuilder_.getMessageOrBuilder();
        } else {
          return errorMsg_ == null ?
              ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
        }
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ErrorMessageResponse.ErrorMessage, ErrorMessageResponse.ErrorMessage.Builder, ErrorMessageResponse.ErrorMessageOrBuilder>
          getErrorMsgFieldBuilder() {
        if (errorMsgBuilder_ == null) {
          errorMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ErrorMessageResponse.ErrorMessage, ErrorMessageResponse.ErrorMessage.Builder, ErrorMessageResponse.ErrorMessageOrBuilder>(
                  getErrorMsg(),
                  getParentForChildren(),
                  isClean());
          errorMsg_ = null;
        }
        return errorMsgBuilder_;
      }

      private java.util.List<BikeInsurancePayout.BikeInsurancePayoutMessage> bikeInsurancePayoutMessage_ =
        java.util.Collections.emptyList();
      private void ensureBikeInsurancePayoutMessageIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          bikeInsurancePayoutMessage_ = new java.util.ArrayList<BikeInsurancePayout.BikeInsurancePayoutMessage>(bikeInsurancePayoutMessage_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          BikeInsurancePayout.BikeInsurancePayoutMessage, BikeInsurancePayout.BikeInsurancePayoutMessage.Builder, BikeInsurancePayout.BikeInsurancePayoutMessageOrBuilder> bikeInsurancePayoutMessageBuilder_;

      /**
       * <code>repeated .BikeInsurancePayoutMessage bikeInsurancePayoutMessage = 2;</code>
       */
      public java.util.List<BikeInsurancePayout.BikeInsurancePayoutMessage> getBikeInsurancePayoutMessageList() {
        if (bikeInsurancePayoutMessageBuilder_ == null) {
          return java.util.Collections.unmodifiableList(bikeInsurancePayoutMessage_);
        } else {
          return bikeInsurancePayoutMessageBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .BikeInsurancePayoutMessage bikeInsurancePayoutMessage = 2;</code>
       */
      public int getBikeInsurancePayoutMessageCount() {
        if (bikeInsurancePayoutMessageBuilder_ == null) {
          return bikeInsurancePayoutMessage_.size();
        } else {
          return bikeInsurancePayoutMessageBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .BikeInsurancePayoutMessage bikeInsurancePayoutMessage = 2;</code>
       */
      public BikeInsurancePayout.BikeInsurancePayoutMessage getBikeInsurancePayoutMessage(int index) {
        if (bikeInsurancePayoutMessageBuilder_ == null) {
          return bikeInsurancePayoutMessage_.get(index);
        } else {
          return bikeInsurancePayoutMessageBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .BikeInsurancePayoutMessage bikeInsurancePayoutMessage = 2;</code>
       */
      public Builder setBikeInsurancePayoutMessage(
          int index, BikeInsurancePayout.BikeInsurancePayoutMessage value) {
        if (bikeInsurancePayoutMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBikeInsurancePayoutMessageIsMutable();
          bikeInsurancePayoutMessage_.set(index, value);
          onChanged();
        } else {
          bikeInsurancePayoutMessageBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .BikeInsurancePayoutMessage bikeInsurancePayoutMessage = 2;</code>
       */
      public Builder setBikeInsurancePayoutMessage(
          int index, BikeInsurancePayout.BikeInsurancePayoutMessage.Builder builderForValue) {
        if (bikeInsurancePayoutMessageBuilder_ == null) {
          ensureBikeInsurancePayoutMessageIsMutable();
          bikeInsurancePayoutMessage_.set(index, builderForValue.build());
          onChanged();
        } else {
          bikeInsurancePayoutMessageBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .BikeInsurancePayoutMessage bikeInsurancePayoutMessage = 2;</code>
       */
      public Builder addBikeInsurancePayoutMessage(BikeInsurancePayout.BikeInsurancePayoutMessage value) {
        if (bikeInsurancePayoutMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBikeInsurancePayoutMessageIsMutable();
          bikeInsurancePayoutMessage_.add(value);
          onChanged();
        } else {
          bikeInsurancePayoutMessageBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .BikeInsurancePayoutMessage bikeInsurancePayoutMessage = 2;</code>
       */
      public Builder addBikeInsurancePayoutMessage(
          int index, BikeInsurancePayout.BikeInsurancePayoutMessage value) {
        if (bikeInsurancePayoutMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBikeInsurancePayoutMessageIsMutable();
          bikeInsurancePayoutMessage_.add(index, value);
          onChanged();
        } else {
          bikeInsurancePayoutMessageBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .BikeInsurancePayoutMessage bikeInsurancePayoutMessage = 2;</code>
       */
      public Builder addBikeInsurancePayoutMessage(
          BikeInsurancePayout.BikeInsurancePayoutMessage.Builder builderForValue) {
        if (bikeInsurancePayoutMessageBuilder_ == null) {
          ensureBikeInsurancePayoutMessageIsMutable();
          bikeInsurancePayoutMessage_.add(builderForValue.build());
          onChanged();
        } else {
          bikeInsurancePayoutMessageBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .BikeInsurancePayoutMessage bikeInsurancePayoutMessage = 2;</code>
       */
      public Builder addBikeInsurancePayoutMessage(
          int index, BikeInsurancePayout.BikeInsurancePayoutMessage.Builder builderForValue) {
        if (bikeInsurancePayoutMessageBuilder_ == null) {
          ensureBikeInsurancePayoutMessageIsMutable();
          bikeInsurancePayoutMessage_.add(index, builderForValue.build());
          onChanged();
        } else {
          bikeInsurancePayoutMessageBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .BikeInsurancePayoutMessage bikeInsurancePayoutMessage = 2;</code>
       */
      public Builder addAllBikeInsurancePayoutMessage(
          Iterable<? extends BikeInsurancePayout.BikeInsurancePayoutMessage> values) {
        if (bikeInsurancePayoutMessageBuilder_ == null) {
          ensureBikeInsurancePayoutMessageIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, bikeInsurancePayoutMessage_);
          onChanged();
        } else {
          bikeInsurancePayoutMessageBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .BikeInsurancePayoutMessage bikeInsurancePayoutMessage = 2;</code>
       */
      public Builder clearBikeInsurancePayoutMessage() {
        if (bikeInsurancePayoutMessageBuilder_ == null) {
          bikeInsurancePayoutMessage_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          bikeInsurancePayoutMessageBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .BikeInsurancePayoutMessage bikeInsurancePayoutMessage = 2;</code>
       */
      public Builder removeBikeInsurancePayoutMessage(int index) {
        if (bikeInsurancePayoutMessageBuilder_ == null) {
          ensureBikeInsurancePayoutMessageIsMutable();
          bikeInsurancePayoutMessage_.remove(index);
          onChanged();
        } else {
          bikeInsurancePayoutMessageBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .BikeInsurancePayoutMessage bikeInsurancePayoutMessage = 2;</code>
       */
      public BikeInsurancePayout.BikeInsurancePayoutMessage.Builder getBikeInsurancePayoutMessageBuilder(
          int index) {
        return getBikeInsurancePayoutMessageFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .BikeInsurancePayoutMessage bikeInsurancePayoutMessage = 2;</code>
       */
      public BikeInsurancePayout.BikeInsurancePayoutMessageOrBuilder getBikeInsurancePayoutMessageOrBuilder(
          int index) {
        if (bikeInsurancePayoutMessageBuilder_ == null) {
          return bikeInsurancePayoutMessage_.get(index);  } else {
          return bikeInsurancePayoutMessageBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .BikeInsurancePayoutMessage bikeInsurancePayoutMessage = 2;</code>
       */
      public java.util.List<? extends BikeInsurancePayout.BikeInsurancePayoutMessageOrBuilder>
           getBikeInsurancePayoutMessageOrBuilderList() {
        if (bikeInsurancePayoutMessageBuilder_ != null) {
          return bikeInsurancePayoutMessageBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(bikeInsurancePayoutMessage_);
        }
      }
      /**
       * <code>repeated .BikeInsurancePayoutMessage bikeInsurancePayoutMessage = 2;</code>
       */
      public BikeInsurancePayout.BikeInsurancePayoutMessage.Builder addBikeInsurancePayoutMessageBuilder() {
        return getBikeInsurancePayoutMessageFieldBuilder().addBuilder(
            BikeInsurancePayout.BikeInsurancePayoutMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .BikeInsurancePayoutMessage bikeInsurancePayoutMessage = 2;</code>
       */
      public BikeInsurancePayout.BikeInsurancePayoutMessage.Builder addBikeInsurancePayoutMessageBuilder(
          int index) {
        return getBikeInsurancePayoutMessageFieldBuilder().addBuilder(
            index, BikeInsurancePayout.BikeInsurancePayoutMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .BikeInsurancePayoutMessage bikeInsurancePayoutMessage = 2;</code>
       */
      public java.util.List<BikeInsurancePayout.BikeInsurancePayoutMessage.Builder>
           getBikeInsurancePayoutMessageBuilderList() {
        return getBikeInsurancePayoutMessageFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          BikeInsurancePayout.BikeInsurancePayoutMessage, BikeInsurancePayout.BikeInsurancePayoutMessage.Builder, BikeInsurancePayout.BikeInsurancePayoutMessageOrBuilder>
          getBikeInsurancePayoutMessageFieldBuilder() {
        if (bikeInsurancePayoutMessageBuilder_ == null) {
          bikeInsurancePayoutMessageBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              BikeInsurancePayout.BikeInsurancePayoutMessage, BikeInsurancePayout.BikeInsurancePayoutMessage.Builder, BikeInsurancePayout.BikeInsurancePayoutMessageOrBuilder>(
                  bikeInsurancePayoutMessage_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          bikeInsurancePayoutMessage_ = null;
        }
        return bikeInsurancePayoutMessageBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:GetBikeInsurancePayoutResponseMessage)
    }

    // @@protoc_insertion_point(class_scope:GetBikeInsurancePayoutResponseMessage)
    private static final GetBikeInsurancePayoutResponseMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GetBikeInsurancePayoutResponseMessage();
    }

    public static GetBikeInsurancePayoutResponseMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetBikeInsurancePayoutResponseMessage>
        PARSER = new com.google.protobuf.AbstractParser<GetBikeInsurancePayoutResponseMessage>() {
      public GetBikeInsurancePayoutResponseMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetBikeInsurancePayoutResponseMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetBikeInsurancePayoutResponseMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<GetBikeInsurancePayoutResponseMessage> getParserForType() {
      return PARSER;
    }

    public GetBikeInsurancePayoutResponseMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetBikeInsurancePayoutResponseMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetBikeInsurancePayoutResponseMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n$GetBikeInsurancePayoutResponse.proto\032\032" +
      "ErrorMessageResponse.proto\032\031BikeInsuranc" +
      "ePayout.proto\"\211\001\n%GetBikeInsurancePayout" +
      "ResponseMessage\022\037\n\010errorMsg\030\001 \001(\0132\r.Erro" +
      "rMessage\022?\n\032bikeInsurancePayoutMessage\030\002" +
      " \003(\0132\033.BikeInsurancePayoutMessageB?\n\035com" +
      ".yzh.rfidbike.app.responseB\036GetBikeInsur" +
      "ancePayoutResponseb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ErrorMessageResponse.getDescriptor(),
          BikeInsurancePayout.getDescriptor(),
        }, assigner);
    internal_static_GetBikeInsurancePayoutResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetBikeInsurancePayoutResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetBikeInsurancePayoutResponseMessage_descriptor,
        new String[] { "ErrorMsg", "BikeInsurancePayoutMessage", });
    ErrorMessageResponse.getDescriptor();
    BikeInsurancePayout.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
