// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetInsuranceMessageRespone.proto

package com.yzh.rfidbike.app.response;

public final class GetInsuranceMessageResponse {
  private GetInsuranceMessageResponse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetInsuranceMessageResponseMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetInsuranceMessageResponseMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    boolean hasErrorMsg();
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    ErrorMessageResponse.ErrorMessage getErrorMsg();
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder();

    /**
     * <code>optional string isLastPage = 2;</code>
     */
    String getIsLastPage();
    /**
     * <code>optional string isLastPage = 2;</code>
     */
    com.google.protobuf.ByteString
        getIsLastPageBytes();

    /**
     * <code>repeated .InsuranceMessageMessage InsuranceMessage = 3;</code>
     */
    java.util.List<InsuranceMessage.InsuranceMessageMessage>
        getInsuranceMessageList();
    /**
     * <code>repeated .InsuranceMessageMessage InsuranceMessage = 3;</code>
     */
    InsuranceMessage.InsuranceMessageMessage getInsuranceMessage(int index);
    /**
     * <code>repeated .InsuranceMessageMessage InsuranceMessage = 3;</code>
     */
    int getInsuranceMessageCount();
    /**
     * <code>repeated .InsuranceMessageMessage InsuranceMessage = 3;</code>
     */
    java.util.List<? extends InsuranceMessage.InsuranceMessageMessageOrBuilder>
        getInsuranceMessageOrBuilderList();
    /**
     * <code>repeated .InsuranceMessageMessage InsuranceMessage = 3;</code>
     */
    InsuranceMessage.InsuranceMessageMessageOrBuilder getInsuranceMessageOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code GetInsuranceMessageResponseMessage}
   */
  public  static final class GetInsuranceMessageResponseMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetInsuranceMessageResponseMessage)
      GetInsuranceMessageResponseMessageOrBuilder {
    // Use GetInsuranceMessageResponseMessage.newBuilder() to construct.
    private GetInsuranceMessageResponseMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetInsuranceMessageResponseMessage() {
      isLastPage_ = "";
      insuranceMessage_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetInsuranceMessageResponseMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              ErrorMessageResponse.ErrorMessage.Builder subBuilder = null;
              if (errorMsg_ != null) {
                subBuilder = errorMsg_.toBuilder();
              }
              errorMsg_ = input.readMessage(ErrorMessageResponse.ErrorMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(errorMsg_);
                errorMsg_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              isLastPage_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                insuranceMessage_ = new java.util.ArrayList<InsuranceMessage.InsuranceMessageMessage>();
                mutable_bitField0_ |= 0x00000004;
              }
              insuranceMessage_.add(
                  input.readMessage(InsuranceMessage.InsuranceMessageMessage.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          insuranceMessage_ = java.util.Collections.unmodifiableList(insuranceMessage_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GetInsuranceMessageResponse.internal_static_GetInsuranceMessageResponseMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GetInsuranceMessageResponse.internal_static_GetInsuranceMessageResponseMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GetInsuranceMessageResponseMessage.class, Builder.class);
    }

    private int bitField0_;
    public static final int ERRORMSG_FIELD_NUMBER = 1;
    private ErrorMessageResponse.ErrorMessage errorMsg_;
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public boolean hasErrorMsg() {
      return errorMsg_ != null;
    }
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public ErrorMessageResponse.ErrorMessage getErrorMsg() {
      return errorMsg_ == null ? ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
    }
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder() {
      return getErrorMsg();
    }

    public static final int ISLASTPAGE_FIELD_NUMBER = 2;
    private volatile Object isLastPage_;
    /**
     * <code>optional string isLastPage = 2;</code>
     */
    public String getIsLastPage() {
      Object ref = isLastPage_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        isLastPage_ = s;
        return s;
      }
    }
    /**
     * <code>optional string isLastPage = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIsLastPageBytes() {
      Object ref = isLastPage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        isLastPage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INSURANCEMESSAGE_FIELD_NUMBER = 3;
    private java.util.List<InsuranceMessage.InsuranceMessageMessage> insuranceMessage_;
    /**
     * <code>repeated .InsuranceMessageMessage InsuranceMessage = 3;</code>
     */
    public java.util.List<InsuranceMessage.InsuranceMessageMessage> getInsuranceMessageList() {
      return insuranceMessage_;
    }
    /**
     * <code>repeated .InsuranceMessageMessage InsuranceMessage = 3;</code>
     */
    public java.util.List<? extends InsuranceMessage.InsuranceMessageMessageOrBuilder>
        getInsuranceMessageOrBuilderList() {
      return insuranceMessage_;
    }
    /**
     * <code>repeated .InsuranceMessageMessage InsuranceMessage = 3;</code>
     */
    public int getInsuranceMessageCount() {
      return insuranceMessage_.size();
    }
    /**
     * <code>repeated .InsuranceMessageMessage InsuranceMessage = 3;</code>
     */
    public InsuranceMessage.InsuranceMessageMessage getInsuranceMessage(int index) {
      return insuranceMessage_.get(index);
    }
    /**
     * <code>repeated .InsuranceMessageMessage InsuranceMessage = 3;</code>
     */
    public InsuranceMessage.InsuranceMessageMessageOrBuilder getInsuranceMessageOrBuilder(
        int index) {
      return insuranceMessage_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (errorMsg_ != null) {
        output.writeMessage(1, getErrorMsg());
      }
      if (!getIsLastPageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, isLastPage_);
      }
      for (int i = 0; i < insuranceMessage_.size(); i++) {
        output.writeMessage(3, insuranceMessage_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (errorMsg_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getErrorMsg());
      }
      if (!getIsLastPageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, isLastPage_);
      }
      for (int i = 0; i < insuranceMessage_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, insuranceMessage_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GetInsuranceMessageResponseMessage)) {
        return super.equals(obj);
      }
      GetInsuranceMessageResponseMessage other = (GetInsuranceMessageResponseMessage) obj;

      boolean result = true;
      result = result && (hasErrorMsg() == other.hasErrorMsg());
      if (hasErrorMsg()) {
        result = result && getErrorMsg()
            .equals(other.getErrorMsg());
      }
      result = result && getIsLastPage()
          .equals(other.getIsLastPage());
      result = result && getInsuranceMessageList()
          .equals(other.getInsuranceMessageList());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasErrorMsg()) {
        hash = (37 * hash) + ERRORMSG_FIELD_NUMBER;
        hash = (53 * hash) + getErrorMsg().hashCode();
      }
      hash = (37 * hash) + ISLASTPAGE_FIELD_NUMBER;
      hash = (53 * hash) + getIsLastPage().hashCode();
      if (getInsuranceMessageCount() > 0) {
        hash = (37 * hash) + INSURANCEMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getInsuranceMessageList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GetInsuranceMessageResponseMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GetInsuranceMessageResponseMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GetInsuranceMessageResponseMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GetInsuranceMessageResponseMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GetInsuranceMessageResponseMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GetInsuranceMessageResponseMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GetInsuranceMessageResponseMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GetInsuranceMessageResponseMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GetInsuranceMessageResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GetInsuranceMessageResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GetInsuranceMessageResponseMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetInsuranceMessageResponseMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetInsuranceMessageResponseMessage)
        GetInsuranceMessageResponseMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GetInsuranceMessageResponse.internal_static_GetInsuranceMessageResponseMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GetInsuranceMessageResponse.internal_static_GetInsuranceMessageResponseMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GetInsuranceMessageResponseMessage.class, Builder.class);
      }

      // Construct using com.yzh.rfidbike.app.response.GetInsuranceMessageResponse.GetInsuranceMessageResponseMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getInsuranceMessageFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (errorMsgBuilder_ == null) {
          errorMsg_ = null;
        } else {
          errorMsg_ = null;
          errorMsgBuilder_ = null;
        }
        isLastPage_ = "";

        if (insuranceMessageBuilder_ == null) {
          insuranceMessage_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          insuranceMessageBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GetInsuranceMessageResponse.internal_static_GetInsuranceMessageResponseMessage_descriptor;
      }

      public GetInsuranceMessageResponseMessage getDefaultInstanceForType() {
        return GetInsuranceMessageResponseMessage.getDefaultInstance();
      }

      public GetInsuranceMessageResponseMessage build() {
        GetInsuranceMessageResponseMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public GetInsuranceMessageResponseMessage buildPartial() {
        GetInsuranceMessageResponseMessage result = new GetInsuranceMessageResponseMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (errorMsgBuilder_ == null) {
          result.errorMsg_ = errorMsg_;
        } else {
          result.errorMsg_ = errorMsgBuilder_.build();
        }
        result.isLastPage_ = isLastPage_;
        if (insuranceMessageBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            insuranceMessage_ = java.util.Collections.unmodifiableList(insuranceMessage_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.insuranceMessage_ = insuranceMessage_;
        } else {
          result.insuranceMessage_ = insuranceMessageBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GetInsuranceMessageResponseMessage) {
          return mergeFrom((GetInsuranceMessageResponseMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GetInsuranceMessageResponseMessage other) {
        if (other == GetInsuranceMessageResponseMessage.getDefaultInstance()) return this;
        if (other.hasErrorMsg()) {
          mergeErrorMsg(other.getErrorMsg());
        }
        if (!other.getIsLastPage().isEmpty()) {
          isLastPage_ = other.isLastPage_;
          onChanged();
        }
        if (insuranceMessageBuilder_ == null) {
          if (!other.insuranceMessage_.isEmpty()) {
            if (insuranceMessage_.isEmpty()) {
              insuranceMessage_ = other.insuranceMessage_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureInsuranceMessageIsMutable();
              insuranceMessage_.addAll(other.insuranceMessage_);
            }
            onChanged();
          }
        } else {
          if (!other.insuranceMessage_.isEmpty()) {
            if (insuranceMessageBuilder_.isEmpty()) {
              insuranceMessageBuilder_.dispose();
              insuranceMessageBuilder_ = null;
              insuranceMessage_ = other.insuranceMessage_;
              bitField0_ = (bitField0_ & ~0x00000004);
              insuranceMessageBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getInsuranceMessageFieldBuilder() : null;
            } else {
              insuranceMessageBuilder_.addAllMessages(other.insuranceMessage_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GetInsuranceMessageResponseMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GetInsuranceMessageResponseMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private ErrorMessageResponse.ErrorMessage errorMsg_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          ErrorMessageResponse.ErrorMessage, ErrorMessageResponse.ErrorMessage.Builder, ErrorMessageResponse.ErrorMessageOrBuilder> errorMsgBuilder_;
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public boolean hasErrorMsg() {
        return errorMsgBuilder_ != null || errorMsg_ != null;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public ErrorMessageResponse.ErrorMessage getErrorMsg() {
        if (errorMsgBuilder_ == null) {
          return errorMsg_ == null ? ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
        } else {
          return errorMsgBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder setErrorMsg(ErrorMessageResponse.ErrorMessage value) {
        if (errorMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          errorMsg_ = value;
          onChanged();
        } else {
          errorMsgBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder setErrorMsg(
          ErrorMessageResponse.ErrorMessage.Builder builderForValue) {
        if (errorMsgBuilder_ == null) {
          errorMsg_ = builderForValue.build();
          onChanged();
        } else {
          errorMsgBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder mergeErrorMsg(ErrorMessageResponse.ErrorMessage value) {
        if (errorMsgBuilder_ == null) {
          if (errorMsg_ != null) {
            errorMsg_ =
              ErrorMessageResponse.ErrorMessage.newBuilder(errorMsg_).mergeFrom(value).buildPartial();
          } else {
            errorMsg_ = value;
          }
          onChanged();
        } else {
          errorMsgBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder clearErrorMsg() {
        if (errorMsgBuilder_ == null) {
          errorMsg_ = null;
          onChanged();
        } else {
          errorMsg_ = null;
          errorMsgBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public ErrorMessageResponse.ErrorMessage.Builder getErrorMsgBuilder() {
        
        onChanged();
        return getErrorMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder() {
        if (errorMsgBuilder_ != null) {
          return errorMsgBuilder_.getMessageOrBuilder();
        } else {
          return errorMsg_ == null ?
              ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
        }
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ErrorMessageResponse.ErrorMessage, ErrorMessageResponse.ErrorMessage.Builder, ErrorMessageResponse.ErrorMessageOrBuilder>
          getErrorMsgFieldBuilder() {
        if (errorMsgBuilder_ == null) {
          errorMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ErrorMessageResponse.ErrorMessage, ErrorMessageResponse.ErrorMessage.Builder, ErrorMessageResponse.ErrorMessageOrBuilder>(
                  getErrorMsg(),
                  getParentForChildren(),
                  isClean());
          errorMsg_ = null;
        }
        return errorMsgBuilder_;
      }

      private Object isLastPage_ = "";
      /**
       * <code>optional string isLastPage = 2;</code>
       */
      public String getIsLastPage() {
        Object ref = isLastPage_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          isLastPage_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string isLastPage = 2;</code>
       */
      public com.google.protobuf.ByteString
          getIsLastPageBytes() {
        Object ref = isLastPage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          isLastPage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string isLastPage = 2;</code>
       */
      public Builder setIsLastPage(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        isLastPage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string isLastPage = 2;</code>
       */
      public Builder clearIsLastPage() {
        
        isLastPage_ = getDefaultInstance().getIsLastPage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string isLastPage = 2;</code>
       */
      public Builder setIsLastPageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        isLastPage_ = value;
        onChanged();
        return this;
      }

      private java.util.List<InsuranceMessage.InsuranceMessageMessage> insuranceMessage_ =
        java.util.Collections.emptyList();
      private void ensureInsuranceMessageIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          insuranceMessage_ = new java.util.ArrayList<InsuranceMessage.InsuranceMessageMessage>(insuranceMessage_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          InsuranceMessage.InsuranceMessageMessage, InsuranceMessage.InsuranceMessageMessage.Builder, InsuranceMessage.InsuranceMessageMessageOrBuilder> insuranceMessageBuilder_;

      /**
       * <code>repeated .InsuranceMessageMessage InsuranceMessage = 3;</code>
       */
      public java.util.List<InsuranceMessage.InsuranceMessageMessage> getInsuranceMessageList() {
        if (insuranceMessageBuilder_ == null) {
          return java.util.Collections.unmodifiableList(insuranceMessage_);
        } else {
          return insuranceMessageBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .InsuranceMessageMessage InsuranceMessage = 3;</code>
       */
      public int getInsuranceMessageCount() {
        if (insuranceMessageBuilder_ == null) {
          return insuranceMessage_.size();
        } else {
          return insuranceMessageBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .InsuranceMessageMessage InsuranceMessage = 3;</code>
       */
      public InsuranceMessage.InsuranceMessageMessage getInsuranceMessage(int index) {
        if (insuranceMessageBuilder_ == null) {
          return insuranceMessage_.get(index);
        } else {
          return insuranceMessageBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .InsuranceMessageMessage InsuranceMessage = 3;</code>
       */
      public Builder setInsuranceMessage(
          int index, InsuranceMessage.InsuranceMessageMessage value) {
        if (insuranceMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInsuranceMessageIsMutable();
          insuranceMessage_.set(index, value);
          onChanged();
        } else {
          insuranceMessageBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .InsuranceMessageMessage InsuranceMessage = 3;</code>
       */
      public Builder setInsuranceMessage(
          int index, InsuranceMessage.InsuranceMessageMessage.Builder builderForValue) {
        if (insuranceMessageBuilder_ == null) {
          ensureInsuranceMessageIsMutable();
          insuranceMessage_.set(index, builderForValue.build());
          onChanged();
        } else {
          insuranceMessageBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .InsuranceMessageMessage InsuranceMessage = 3;</code>
       */
      public Builder addInsuranceMessage(InsuranceMessage.InsuranceMessageMessage value) {
        if (insuranceMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInsuranceMessageIsMutable();
          insuranceMessage_.add(value);
          onChanged();
        } else {
          insuranceMessageBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .InsuranceMessageMessage InsuranceMessage = 3;</code>
       */
      public Builder addInsuranceMessage(
          int index, InsuranceMessage.InsuranceMessageMessage value) {
        if (insuranceMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInsuranceMessageIsMutable();
          insuranceMessage_.add(index, value);
          onChanged();
        } else {
          insuranceMessageBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .InsuranceMessageMessage InsuranceMessage = 3;</code>
       */
      public Builder addInsuranceMessage(
          InsuranceMessage.InsuranceMessageMessage.Builder builderForValue) {
        if (insuranceMessageBuilder_ == null) {
          ensureInsuranceMessageIsMutable();
          insuranceMessage_.add(builderForValue.build());
          onChanged();
        } else {
          insuranceMessageBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .InsuranceMessageMessage InsuranceMessage = 3;</code>
       */
      public Builder addInsuranceMessage(
          int index, InsuranceMessage.InsuranceMessageMessage.Builder builderForValue) {
        if (insuranceMessageBuilder_ == null) {
          ensureInsuranceMessageIsMutable();
          insuranceMessage_.add(index, builderForValue.build());
          onChanged();
        } else {
          insuranceMessageBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .InsuranceMessageMessage InsuranceMessage = 3;</code>
       */
      public Builder addAllInsuranceMessage(
          Iterable<? extends InsuranceMessage.InsuranceMessageMessage> values) {
        if (insuranceMessageBuilder_ == null) {
          ensureInsuranceMessageIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, insuranceMessage_);
          onChanged();
        } else {
          insuranceMessageBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .InsuranceMessageMessage InsuranceMessage = 3;</code>
       */
      public Builder clearInsuranceMessage() {
        if (insuranceMessageBuilder_ == null) {
          insuranceMessage_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          insuranceMessageBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .InsuranceMessageMessage InsuranceMessage = 3;</code>
       */
      public Builder removeInsuranceMessage(int index) {
        if (insuranceMessageBuilder_ == null) {
          ensureInsuranceMessageIsMutable();
          insuranceMessage_.remove(index);
          onChanged();
        } else {
          insuranceMessageBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .InsuranceMessageMessage InsuranceMessage = 3;</code>
       */
      public InsuranceMessage.InsuranceMessageMessage.Builder getInsuranceMessageBuilder(
          int index) {
        return getInsuranceMessageFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .InsuranceMessageMessage InsuranceMessage = 3;</code>
       */
      public InsuranceMessage.InsuranceMessageMessageOrBuilder getInsuranceMessageOrBuilder(
          int index) {
        if (insuranceMessageBuilder_ == null) {
          return insuranceMessage_.get(index);  } else {
          return insuranceMessageBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .InsuranceMessageMessage InsuranceMessage = 3;</code>
       */
      public java.util.List<? extends InsuranceMessage.InsuranceMessageMessageOrBuilder>
           getInsuranceMessageOrBuilderList() {
        if (insuranceMessageBuilder_ != null) {
          return insuranceMessageBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(insuranceMessage_);
        }
      }
      /**
       * <code>repeated .InsuranceMessageMessage InsuranceMessage = 3;</code>
       */
      public InsuranceMessage.InsuranceMessageMessage.Builder addInsuranceMessageBuilder() {
        return getInsuranceMessageFieldBuilder().addBuilder(
            InsuranceMessage.InsuranceMessageMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .InsuranceMessageMessage InsuranceMessage = 3;</code>
       */
      public InsuranceMessage.InsuranceMessageMessage.Builder addInsuranceMessageBuilder(
          int index) {
        return getInsuranceMessageFieldBuilder().addBuilder(
            index, InsuranceMessage.InsuranceMessageMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .InsuranceMessageMessage InsuranceMessage = 3;</code>
       */
      public java.util.List<InsuranceMessage.InsuranceMessageMessage.Builder>
           getInsuranceMessageBuilderList() {
        return getInsuranceMessageFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          InsuranceMessage.InsuranceMessageMessage, InsuranceMessage.InsuranceMessageMessage.Builder, InsuranceMessage.InsuranceMessageMessageOrBuilder>
          getInsuranceMessageFieldBuilder() {
        if (insuranceMessageBuilder_ == null) {
          insuranceMessageBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              InsuranceMessage.InsuranceMessageMessage, InsuranceMessage.InsuranceMessageMessage.Builder, InsuranceMessage.InsuranceMessageMessageOrBuilder>(
                  insuranceMessage_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          insuranceMessage_ = null;
        }
        return insuranceMessageBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:GetInsuranceMessageResponseMessage)
    }

    // @@protoc_insertion_point(class_scope:GetInsuranceMessageResponseMessage)
    private static final GetInsuranceMessageResponseMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GetInsuranceMessageResponseMessage();
    }

    public static GetInsuranceMessageResponseMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetInsuranceMessageResponseMessage>
        PARSER = new com.google.protobuf.AbstractParser<GetInsuranceMessageResponseMessage>() {
      public GetInsuranceMessageResponseMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetInsuranceMessageResponseMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetInsuranceMessageResponseMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<GetInsuranceMessageResponseMessage> getParserForType() {
      return PARSER;
    }

    public GetInsuranceMessageResponseMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetInsuranceMessageResponseMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetInsuranceMessageResponseMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n GetInsuranceMessageRespone.proto\032\032Erro" +
      "rMessageResponse.proto\032\026InsuranceMessage" +
      ".proto\"\215\001\n\"GetInsuranceMessageResponseMe" +
      "ssage\022\037\n\010errorMsg\030\001 \001(\0132\r.ErrorMessage\022\022" +
      "\n\nisLastPage\030\002 \001(\t\0222\n\020InsuranceMessage\030\003" +
      " \003(\0132\030.InsuranceMessageMessageB<\n\035com.yz" +
      "h.rfidbike.app.responseB\033GetInsuranceMes" +
      "sageResponseb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ErrorMessageResponse.getDescriptor(),
          InsuranceMessage.getDescriptor(),
        }, assigner);
    internal_static_GetInsuranceMessageResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetInsuranceMessageResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetInsuranceMessageResponseMessage_descriptor,
        new String[] { "ErrorMsg", "IsLastPage", "InsuranceMessage", });
    ErrorMessageResponse.getDescriptor();
    InsuranceMessage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
