// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AddBikeInsuranceRequest.proto

package com.yzh.rfidbike.app.request;

public final class AddBikeInsuranceRequest {
  private AddBikeInsuranceRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AddBikeInsuranceRequestMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AddBikeInsuranceRequestMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string session = 1;</code>
     */
    String getSession();
    /**
     * <code>optional string session = 1;</code>
     */
    com.google.protobuf.ByteString
        getSessionBytes();

    /**
     * <code>optional .BikeInsuranceMessage bikeInsuranceMessage = 2;</code>
     */
    boolean hasBikeInsuranceMessage();
    /**
     * <code>optional .BikeInsuranceMessage bikeInsuranceMessage = 2;</code>
     */
    com.yzh.rfidbike.app.response.BikeInsurance.BikeInsuranceMessage getBikeInsuranceMessage();
    /**
     * <code>optional .BikeInsuranceMessage bikeInsuranceMessage = 2;</code>
     */
    com.yzh.rfidbike.app.response.BikeInsurance.BikeInsuranceMessageOrBuilder getBikeInsuranceMessageOrBuilder();
  }
  /**
   * <pre>
   *  添加车辆保险或者续保--车主App
   * </pre>
   *
   * Protobuf type {@code AddBikeInsuranceRequestMessage}
   */
  public  static final class AddBikeInsuranceRequestMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AddBikeInsuranceRequestMessage)
      AddBikeInsuranceRequestMessageOrBuilder {
    // Use AddBikeInsuranceRequestMessage.newBuilder() to construct.
    private AddBikeInsuranceRequestMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AddBikeInsuranceRequestMessage() {
      session_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private AddBikeInsuranceRequestMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              session_ = s;
              break;
            }
            case 18: {
              com.yzh.rfidbike.app.response.BikeInsurance.BikeInsuranceMessage.Builder subBuilder = null;
              if (bikeInsuranceMessage_ != null) {
                subBuilder = bikeInsuranceMessage_.toBuilder();
              }
              bikeInsuranceMessage_ = input.readMessage(com.yzh.rfidbike.app.response.BikeInsurance.BikeInsuranceMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(bikeInsuranceMessage_);
                bikeInsuranceMessage_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AddBikeInsuranceRequest.internal_static_AddBikeInsuranceRequestMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AddBikeInsuranceRequest.internal_static_AddBikeInsuranceRequestMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AddBikeInsuranceRequestMessage.class, Builder.class);
    }

    public static final int SESSION_FIELD_NUMBER = 1;
    private volatile Object session_;
    /**
     * <code>optional string session = 1;</code>
     */
    public String getSession() {
      Object ref = session_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        session_ = s;
        return s;
      }
    }
    /**
     * <code>optional string session = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSessionBytes() {
      Object ref = session_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        session_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BIKEINSURANCEMESSAGE_FIELD_NUMBER = 2;
    private com.yzh.rfidbike.app.response.BikeInsurance.BikeInsuranceMessage bikeInsuranceMessage_;
    /**
     * <code>optional .BikeInsuranceMessage bikeInsuranceMessage = 2;</code>
     */
    public boolean hasBikeInsuranceMessage() {
      return bikeInsuranceMessage_ != null;
    }
    /**
     * <code>optional .BikeInsuranceMessage bikeInsuranceMessage = 2;</code>
     */
    public com.yzh.rfidbike.app.response.BikeInsurance.BikeInsuranceMessage getBikeInsuranceMessage() {
      return bikeInsuranceMessage_ == null ? com.yzh.rfidbike.app.response.BikeInsurance.BikeInsuranceMessage.getDefaultInstance() : bikeInsuranceMessage_;
    }
    /**
     * <code>optional .BikeInsuranceMessage bikeInsuranceMessage = 2;</code>
     */
    public com.yzh.rfidbike.app.response.BikeInsurance.BikeInsuranceMessageOrBuilder getBikeInsuranceMessageOrBuilder() {
      return getBikeInsuranceMessage();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSessionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, session_);
      }
      if (bikeInsuranceMessage_ != null) {
        output.writeMessage(2, getBikeInsuranceMessage());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSessionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, session_);
      }
      if (bikeInsuranceMessage_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getBikeInsuranceMessage());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof AddBikeInsuranceRequestMessage)) {
        return super.equals(obj);
      }
      AddBikeInsuranceRequestMessage other = (AddBikeInsuranceRequestMessage) obj;

      boolean result = true;
      result = result && getSession()
          .equals(other.getSession());
      result = result && (hasBikeInsuranceMessage() == other.hasBikeInsuranceMessage());
      if (hasBikeInsuranceMessage()) {
        result = result && getBikeInsuranceMessage()
            .equals(other.getBikeInsuranceMessage());
      }
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + SESSION_FIELD_NUMBER;
      hash = (53 * hash) + getSession().hashCode();
      if (hasBikeInsuranceMessage()) {
        hash = (37 * hash) + BIKEINSURANCEMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getBikeInsuranceMessage().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static AddBikeInsuranceRequestMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AddBikeInsuranceRequestMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AddBikeInsuranceRequestMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AddBikeInsuranceRequestMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AddBikeInsuranceRequestMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AddBikeInsuranceRequestMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static AddBikeInsuranceRequestMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static AddBikeInsuranceRequestMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static AddBikeInsuranceRequestMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AddBikeInsuranceRequestMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AddBikeInsuranceRequestMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *  添加车辆保险或者续保--车主App
     * </pre>
     *
     * Protobuf type {@code AddBikeInsuranceRequestMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AddBikeInsuranceRequestMessage)
        AddBikeInsuranceRequestMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AddBikeInsuranceRequest.internal_static_AddBikeInsuranceRequestMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AddBikeInsuranceRequest.internal_static_AddBikeInsuranceRequestMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AddBikeInsuranceRequestMessage.class, Builder.class);
      }

      // Construct using com.yzh.rfidbike.app.request.AddBikeInsuranceRequest.AddBikeInsuranceRequestMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        session_ = "";

        if (bikeInsuranceMessageBuilder_ == null) {
          bikeInsuranceMessage_ = null;
        } else {
          bikeInsuranceMessage_ = null;
          bikeInsuranceMessageBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AddBikeInsuranceRequest.internal_static_AddBikeInsuranceRequestMessage_descriptor;
      }

      public AddBikeInsuranceRequestMessage getDefaultInstanceForType() {
        return AddBikeInsuranceRequestMessage.getDefaultInstance();
      }

      public AddBikeInsuranceRequestMessage build() {
        AddBikeInsuranceRequestMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public AddBikeInsuranceRequestMessage buildPartial() {
        AddBikeInsuranceRequestMessage result = new AddBikeInsuranceRequestMessage(this);
        result.session_ = session_;
        if (bikeInsuranceMessageBuilder_ == null) {
          result.bikeInsuranceMessage_ = bikeInsuranceMessage_;
        } else {
          result.bikeInsuranceMessage_ = bikeInsuranceMessageBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AddBikeInsuranceRequestMessage) {
          return mergeFrom((AddBikeInsuranceRequestMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AddBikeInsuranceRequestMessage other) {
        if (other == AddBikeInsuranceRequestMessage.getDefaultInstance()) return this;
        if (!other.getSession().isEmpty()) {
          session_ = other.session_;
          onChanged();
        }
        if (other.hasBikeInsuranceMessage()) {
          mergeBikeInsuranceMessage(other.getBikeInsuranceMessage());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        AddBikeInsuranceRequestMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (AddBikeInsuranceRequestMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object session_ = "";
      /**
       * <code>optional string session = 1;</code>
       */
      public String getSession() {
        Object ref = session_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          session_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string session = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSessionBytes() {
        Object ref = session_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          session_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string session = 1;</code>
       */
      public Builder setSession(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        session_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string session = 1;</code>
       */
      public Builder clearSession() {
        
        session_ = getDefaultInstance().getSession();
        onChanged();
        return this;
      }
      /**
       * <code>optional string session = 1;</code>
       */
      public Builder setSessionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        session_ = value;
        onChanged();
        return this;
      }

      private com.yzh.rfidbike.app.response.BikeInsurance.BikeInsuranceMessage bikeInsuranceMessage_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.yzh.rfidbike.app.response.BikeInsurance.BikeInsuranceMessage, com.yzh.rfidbike.app.response.BikeInsurance.BikeInsuranceMessage.Builder, com.yzh.rfidbike.app.response.BikeInsurance.BikeInsuranceMessageOrBuilder> bikeInsuranceMessageBuilder_;
      /**
       * <code>optional .BikeInsuranceMessage bikeInsuranceMessage = 2;</code>
       */
      public boolean hasBikeInsuranceMessage() {
        return bikeInsuranceMessageBuilder_ != null || bikeInsuranceMessage_ != null;
      }
      /**
       * <code>optional .BikeInsuranceMessage bikeInsuranceMessage = 2;</code>
       */
      public com.yzh.rfidbike.app.response.BikeInsurance.BikeInsuranceMessage getBikeInsuranceMessage() {
        if (bikeInsuranceMessageBuilder_ == null) {
          return bikeInsuranceMessage_ == null ? com.yzh.rfidbike.app.response.BikeInsurance.BikeInsuranceMessage.getDefaultInstance() : bikeInsuranceMessage_;
        } else {
          return bikeInsuranceMessageBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .BikeInsuranceMessage bikeInsuranceMessage = 2;</code>
       */
      public Builder setBikeInsuranceMessage(com.yzh.rfidbike.app.response.BikeInsurance.BikeInsuranceMessage value) {
        if (bikeInsuranceMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          bikeInsuranceMessage_ = value;
          onChanged();
        } else {
          bikeInsuranceMessageBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .BikeInsuranceMessage bikeInsuranceMessage = 2;</code>
       */
      public Builder setBikeInsuranceMessage(
          com.yzh.rfidbike.app.response.BikeInsurance.BikeInsuranceMessage.Builder builderForValue) {
        if (bikeInsuranceMessageBuilder_ == null) {
          bikeInsuranceMessage_ = builderForValue.build();
          onChanged();
        } else {
          bikeInsuranceMessageBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .BikeInsuranceMessage bikeInsuranceMessage = 2;</code>
       */
      public Builder mergeBikeInsuranceMessage(com.yzh.rfidbike.app.response.BikeInsurance.BikeInsuranceMessage value) {
        if (bikeInsuranceMessageBuilder_ == null) {
          if (bikeInsuranceMessage_ != null) {
            bikeInsuranceMessage_ =
              com.yzh.rfidbike.app.response.BikeInsurance.BikeInsuranceMessage.newBuilder(bikeInsuranceMessage_).mergeFrom(value).buildPartial();
          } else {
            bikeInsuranceMessage_ = value;
          }
          onChanged();
        } else {
          bikeInsuranceMessageBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .BikeInsuranceMessage bikeInsuranceMessage = 2;</code>
       */
      public Builder clearBikeInsuranceMessage() {
        if (bikeInsuranceMessageBuilder_ == null) {
          bikeInsuranceMessage_ = null;
          onChanged();
        } else {
          bikeInsuranceMessage_ = null;
          bikeInsuranceMessageBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .BikeInsuranceMessage bikeInsuranceMessage = 2;</code>
       */
      public com.yzh.rfidbike.app.response.BikeInsurance.BikeInsuranceMessage.Builder getBikeInsuranceMessageBuilder() {
        
        onChanged();
        return getBikeInsuranceMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .BikeInsuranceMessage bikeInsuranceMessage = 2;</code>
       */
      public com.yzh.rfidbike.app.response.BikeInsurance.BikeInsuranceMessageOrBuilder getBikeInsuranceMessageOrBuilder() {
        if (bikeInsuranceMessageBuilder_ != null) {
          return bikeInsuranceMessageBuilder_.getMessageOrBuilder();
        } else {
          return bikeInsuranceMessage_ == null ?
              com.yzh.rfidbike.app.response.BikeInsurance.BikeInsuranceMessage.getDefaultInstance() : bikeInsuranceMessage_;
        }
      }
      /**
       * <code>optional .BikeInsuranceMessage bikeInsuranceMessage = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.yzh.rfidbike.app.response.BikeInsurance.BikeInsuranceMessage, com.yzh.rfidbike.app.response.BikeInsurance.BikeInsuranceMessage.Builder, com.yzh.rfidbike.app.response.BikeInsurance.BikeInsuranceMessageOrBuilder> 
          getBikeInsuranceMessageFieldBuilder() {
        if (bikeInsuranceMessageBuilder_ == null) {
          bikeInsuranceMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.yzh.rfidbike.app.response.BikeInsurance.BikeInsuranceMessage, com.yzh.rfidbike.app.response.BikeInsurance.BikeInsuranceMessage.Builder, com.yzh.rfidbike.app.response.BikeInsurance.BikeInsuranceMessageOrBuilder>(
                  getBikeInsuranceMessage(),
                  getParentForChildren(),
                  isClean());
          bikeInsuranceMessage_ = null;
        }
        return bikeInsuranceMessageBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:AddBikeInsuranceRequestMessage)
    }

    // @@protoc_insertion_point(class_scope:AddBikeInsuranceRequestMessage)
    private static final AddBikeInsuranceRequestMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AddBikeInsuranceRequestMessage();
    }

    public static AddBikeInsuranceRequestMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AddBikeInsuranceRequestMessage>
        PARSER = new com.google.protobuf.AbstractParser<AddBikeInsuranceRequestMessage>() {
      public AddBikeInsuranceRequestMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AddBikeInsuranceRequestMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AddBikeInsuranceRequestMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<AddBikeInsuranceRequestMessage> getParserForType() {
      return PARSER;
    }

    public AddBikeInsuranceRequestMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddBikeInsuranceRequestMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddBikeInsuranceRequestMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\035AddBikeInsuranceRequest.proto\032\023BikeIns" +
      "urance.proto\"f\n\036AddBikeInsuranceRequestM" +
      "essage\022\017\n\007session\030\001 \001(\t\0223\n\024bikeInsurance" +
      "Message\030\002 \001(\0132\025.BikeInsuranceMessageB7\n\034" +
      "com.yzh.rfidbike.app.requestB\027AddBikeIns" +
      "uranceRequestb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.yzh.rfidbike.app.response.BikeInsurance.getDescriptor(),
        }, assigner);
    internal_static_AddBikeInsuranceRequestMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AddBikeInsuranceRequestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddBikeInsuranceRequestMessage_descriptor,
        new String[] { "Session", "BikeInsuranceMessage", });
    com.yzh.rfidbike.app.response.BikeInsurance.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
