// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ApplyBikeInsuranceCashRequest.proto

package com.yzh.rfidbike.app.request;

public final class ApplyBikeInsuranceCashRequest {
  private ApplyBikeInsuranceCashRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ApplyBikeInsuranceCashRequestMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ApplyBikeInsuranceCashRequestMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *车辆ID
     * </pre>
     *
     * <code>optional int64 bikeId = 1;</code>
     */
    long getBikeId();

    /**
     * <pre>
     *投保ID
     * </pre>
     *
     * <code>optional int64 insuranceId = 2;</code>
     */
    long getInsuranceId();

    /**
     * <pre>
     *会话
     * </pre>
     *
     * <code>optional string session = 4;</code>
     */
    String getSession();
    /**
     * <pre>
     *会话
     * </pre>
     *
     * <code>optional string session = 4;</code>
     */
    com.google.protobuf.ByteString
        getSessionBytes();

    /**
     * <pre>
     *提现类型    0  现金    1  汇款
     * </pre>
     *
     * <code>optional string withdrawType = 5;</code>
     */
    String getWithdrawType();
    /**
     * <pre>
     *提现类型    0  现金    1  汇款
     * </pre>
     *
     * <code>optional string withdrawType = 5;</code>
     */
    com.google.protobuf.ByteString
        getWithdrawTypeBytes();

    /**
     * <pre>
     *提现账号
     * </pre>
     *
     * <code>optional string withdrawAccount = 6;</code>
     */
    String getWithdrawAccount();
    /**
     * <pre>
     *提现账号
     * </pre>
     *
     * <code>optional string withdrawAccount = 6;</code>
     */
    com.google.protobuf.ByteString
        getWithdrawAccountBytes();

    /**
     * <pre>
     *开户行
     * </pre>
     *
     * <code>optional string withdrawBank = 7;</code>
     */
    String getWithdrawBank();
    /**
     * <pre>
     *开户行
     * </pre>
     *
     * <code>optional string withdrawBank = 7;</code>
     */
    com.google.protobuf.ByteString
        getWithdrawBankBytes();

    /**
     * <pre>
     *提现人
     * </pre>
     *
     * <code>optional string name = 8;</code>
     */
    String getName();
    /**
     * <pre>
     *提现人
     * </pre>
     *
     * <code>optional string name = 8;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     *id
     * </pre>
     *
     * <code>optional int64 id = 9;</code>
     */
    long getId();
  }
  /**
   * <pre>
   *申请车辆保险提现请求消息
   * </pre>
   *
   * Protobuf type {@code ApplyBikeInsuranceCashRequestMessage}
   */
  public  static final class ApplyBikeInsuranceCashRequestMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ApplyBikeInsuranceCashRequestMessage)
      ApplyBikeInsuranceCashRequestMessageOrBuilder {
    // Use ApplyBikeInsuranceCashRequestMessage.newBuilder() to construct.
    private ApplyBikeInsuranceCashRequestMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ApplyBikeInsuranceCashRequestMessage() {
      bikeId_ = 0L;
      insuranceId_ = 0L;
      session_ = "";
      withdrawType_ = "";
      withdrawAccount_ = "";
      withdrawBank_ = "";
      name_ = "";
      id_ = 0L;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ApplyBikeInsuranceCashRequestMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              bikeId_ = input.readInt64();
              break;
            }
            case 16: {

              insuranceId_ = input.readInt64();
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              session_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              withdrawType_ = s;
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              withdrawAccount_ = s;
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              withdrawBank_ = s;
              break;
            }
            case 66: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 72: {

              id_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ApplyBikeInsuranceCashRequest.internal_static_ApplyBikeInsuranceCashRequestMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ApplyBikeInsuranceCashRequest.internal_static_ApplyBikeInsuranceCashRequestMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ApplyBikeInsuranceCashRequestMessage.class, Builder.class);
    }

    public static final int BIKEID_FIELD_NUMBER = 1;
    private long bikeId_;
    /**
     * <pre>
     *车辆ID
     * </pre>
     *
     * <code>optional int64 bikeId = 1;</code>
     */
    public long getBikeId() {
      return bikeId_;
    }

    public static final int INSURANCEID_FIELD_NUMBER = 2;
    private long insuranceId_;
    /**
     * <pre>
     *投保ID
     * </pre>
     *
     * <code>optional int64 insuranceId = 2;</code>
     */
    public long getInsuranceId() {
      return insuranceId_;
    }

    public static final int SESSION_FIELD_NUMBER = 4;
    private volatile Object session_;
    /**
     * <pre>
     *会话
     * </pre>
     *
     * <code>optional string session = 4;</code>
     */
    public String getSession() {
      Object ref = session_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        session_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *会话
     * </pre>
     *
     * <code>optional string session = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSessionBytes() {
      Object ref = session_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        session_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WITHDRAWTYPE_FIELD_NUMBER = 5;
    private volatile Object withdrawType_;
    /**
     * <pre>
     *提现类型    0  现金    1  汇款
     * </pre>
     *
     * <code>optional string withdrawType = 5;</code>
     */
    public String getWithdrawType() {
      Object ref = withdrawType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        withdrawType_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *提现类型    0  现金    1  汇款
     * </pre>
     *
     * <code>optional string withdrawType = 5;</code>
     */
    public com.google.protobuf.ByteString
        getWithdrawTypeBytes() {
      Object ref = withdrawType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        withdrawType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WITHDRAWACCOUNT_FIELD_NUMBER = 6;
    private volatile Object withdrawAccount_;
    /**
     * <pre>
     *提现账号
     * </pre>
     *
     * <code>optional string withdrawAccount = 6;</code>
     */
    public String getWithdrawAccount() {
      Object ref = withdrawAccount_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        withdrawAccount_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *提现账号
     * </pre>
     *
     * <code>optional string withdrawAccount = 6;</code>
     */
    public com.google.protobuf.ByteString
        getWithdrawAccountBytes() {
      Object ref = withdrawAccount_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        withdrawAccount_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WITHDRAWBANK_FIELD_NUMBER = 7;
    private volatile Object withdrawBank_;
    /**
     * <pre>
     *开户行
     * </pre>
     *
     * <code>optional string withdrawBank = 7;</code>
     */
    public String getWithdrawBank() {
      Object ref = withdrawBank_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        withdrawBank_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *开户行
     * </pre>
     *
     * <code>optional string withdrawBank = 7;</code>
     */
    public com.google.protobuf.ByteString
        getWithdrawBankBytes() {
      Object ref = withdrawBank_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        withdrawBank_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 8;
    private volatile Object name_;
    /**
     * <pre>
     *提现人
     * </pre>
     *
     * <code>optional string name = 8;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *提现人
     * </pre>
     *
     * <code>optional string name = 8;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 9;
    private long id_;
    /**
     * <pre>
     *id
     * </pre>
     *
     * <code>optional int64 id = 9;</code>
     */
    public long getId() {
      return id_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (bikeId_ != 0L) {
        output.writeInt64(1, bikeId_);
      }
      if (insuranceId_ != 0L) {
        output.writeInt64(2, insuranceId_);
      }
      if (!getSessionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, session_);
      }
      if (!getWithdrawTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, withdrawType_);
      }
      if (!getWithdrawAccountBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, withdrawAccount_);
      }
      if (!getWithdrawBankBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, withdrawBank_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, name_);
      }
      if (id_ != 0L) {
        output.writeInt64(9, id_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (bikeId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, bikeId_);
      }
      if (insuranceId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, insuranceId_);
      }
      if (!getSessionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, session_);
      }
      if (!getWithdrawTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, withdrawType_);
      }
      if (!getWithdrawAccountBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, withdrawAccount_);
      }
      if (!getWithdrawBankBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, withdrawBank_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, name_);
      }
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, id_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ApplyBikeInsuranceCashRequestMessage)) {
        return super.equals(obj);
      }
      ApplyBikeInsuranceCashRequestMessage other = (ApplyBikeInsuranceCashRequestMessage) obj;

      boolean result = true;
      result = result && (getBikeId()
          == other.getBikeId());
      result = result && (getInsuranceId()
          == other.getInsuranceId());
      result = result && getSession()
          .equals(other.getSession());
      result = result && getWithdrawType()
          .equals(other.getWithdrawType());
      result = result && getWithdrawAccount()
          .equals(other.getWithdrawAccount());
      result = result && getWithdrawBank()
          .equals(other.getWithdrawBank());
      result = result && getName()
          .equals(other.getName());
      result = result && (getId()
          == other.getId());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + BIKEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBikeId());
      hash = (37 * hash) + INSURANCEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getInsuranceId());
      hash = (37 * hash) + SESSION_FIELD_NUMBER;
      hash = (53 * hash) + getSession().hashCode();
      hash = (37 * hash) + WITHDRAWTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getWithdrawType().hashCode();
      hash = (37 * hash) + WITHDRAWACCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getWithdrawAccount().hashCode();
      hash = (37 * hash) + WITHDRAWBANK_FIELD_NUMBER;
      hash = (53 * hash) + getWithdrawBank().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ApplyBikeInsuranceCashRequestMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ApplyBikeInsuranceCashRequestMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ApplyBikeInsuranceCashRequestMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ApplyBikeInsuranceCashRequestMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ApplyBikeInsuranceCashRequestMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ApplyBikeInsuranceCashRequestMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ApplyBikeInsuranceCashRequestMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ApplyBikeInsuranceCashRequestMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ApplyBikeInsuranceCashRequestMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ApplyBikeInsuranceCashRequestMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ApplyBikeInsuranceCashRequestMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *申请车辆保险提现请求消息
     * </pre>
     *
     * Protobuf type {@code ApplyBikeInsuranceCashRequestMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ApplyBikeInsuranceCashRequestMessage)
        ApplyBikeInsuranceCashRequestMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ApplyBikeInsuranceCashRequest.internal_static_ApplyBikeInsuranceCashRequestMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ApplyBikeInsuranceCashRequest.internal_static_ApplyBikeInsuranceCashRequestMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ApplyBikeInsuranceCashRequestMessage.class, Builder.class);
      }

      // Construct using com.yzh.rfidbike.app.request.ApplyBikeInsuranceCashRequest.ApplyBikeInsuranceCashRequestMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        bikeId_ = 0L;

        insuranceId_ = 0L;

        session_ = "";

        withdrawType_ = "";

        withdrawAccount_ = "";

        withdrawBank_ = "";

        name_ = "";

        id_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ApplyBikeInsuranceCashRequest.internal_static_ApplyBikeInsuranceCashRequestMessage_descriptor;
      }

      public ApplyBikeInsuranceCashRequestMessage getDefaultInstanceForType() {
        return ApplyBikeInsuranceCashRequestMessage.getDefaultInstance();
      }

      public ApplyBikeInsuranceCashRequestMessage build() {
        ApplyBikeInsuranceCashRequestMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ApplyBikeInsuranceCashRequestMessage buildPartial() {
        ApplyBikeInsuranceCashRequestMessage result = new ApplyBikeInsuranceCashRequestMessage(this);
        result.bikeId_ = bikeId_;
        result.insuranceId_ = insuranceId_;
        result.session_ = session_;
        result.withdrawType_ = withdrawType_;
        result.withdrawAccount_ = withdrawAccount_;
        result.withdrawBank_ = withdrawBank_;
        result.name_ = name_;
        result.id_ = id_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ApplyBikeInsuranceCashRequestMessage) {
          return mergeFrom((ApplyBikeInsuranceCashRequestMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ApplyBikeInsuranceCashRequestMessage other) {
        if (other == ApplyBikeInsuranceCashRequestMessage.getDefaultInstance()) return this;
        if (other.getBikeId() != 0L) {
          setBikeId(other.getBikeId());
        }
        if (other.getInsuranceId() != 0L) {
          setInsuranceId(other.getInsuranceId());
        }
        if (!other.getSession().isEmpty()) {
          session_ = other.session_;
          onChanged();
        }
        if (!other.getWithdrawType().isEmpty()) {
          withdrawType_ = other.withdrawType_;
          onChanged();
        }
        if (!other.getWithdrawAccount().isEmpty()) {
          withdrawAccount_ = other.withdrawAccount_;
          onChanged();
        }
        if (!other.getWithdrawBank().isEmpty()) {
          withdrawBank_ = other.withdrawBank_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ApplyBikeInsuranceCashRequestMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ApplyBikeInsuranceCashRequestMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long bikeId_ ;
      /**
       * <pre>
       *车辆ID
       * </pre>
       *
       * <code>optional int64 bikeId = 1;</code>
       */
      public long getBikeId() {
        return bikeId_;
      }
      /**
       * <pre>
       *车辆ID
       * </pre>
       *
       * <code>optional int64 bikeId = 1;</code>
       */
      public Builder setBikeId(long value) {
        
        bikeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *车辆ID
       * </pre>
       *
       * <code>optional int64 bikeId = 1;</code>
       */
      public Builder clearBikeId() {
        
        bikeId_ = 0L;
        onChanged();
        return this;
      }

      private long insuranceId_ ;
      /**
       * <pre>
       *投保ID
       * </pre>
       *
       * <code>optional int64 insuranceId = 2;</code>
       */
      public long getInsuranceId() {
        return insuranceId_;
      }
      /**
       * <pre>
       *投保ID
       * </pre>
       *
       * <code>optional int64 insuranceId = 2;</code>
       */
      public Builder setInsuranceId(long value) {
        
        insuranceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *投保ID
       * </pre>
       *
       * <code>optional int64 insuranceId = 2;</code>
       */
      public Builder clearInsuranceId() {
        
        insuranceId_ = 0L;
        onChanged();
        return this;
      }

      private Object session_ = "";
      /**
       * <pre>
       *会话
       * </pre>
       *
       * <code>optional string session = 4;</code>
       */
      public String getSession() {
        Object ref = session_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          session_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *会话
       * </pre>
       *
       * <code>optional string session = 4;</code>
       */
      public com.google.protobuf.ByteString
          getSessionBytes() {
        Object ref = session_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          session_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *会话
       * </pre>
       *
       * <code>optional string session = 4;</code>
       */
      public Builder setSession(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        session_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *会话
       * </pre>
       *
       * <code>optional string session = 4;</code>
       */
      public Builder clearSession() {
        
        session_ = getDefaultInstance().getSession();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *会话
       * </pre>
       *
       * <code>optional string session = 4;</code>
       */
      public Builder setSessionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        session_ = value;
        onChanged();
        return this;
      }

      private Object withdrawType_ = "";
      /**
       * <pre>
       *提现类型    0  现金    1  汇款
       * </pre>
       *
       * <code>optional string withdrawType = 5;</code>
       */
      public String getWithdrawType() {
        Object ref = withdrawType_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          withdrawType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *提现类型    0  现金    1  汇款
       * </pre>
       *
       * <code>optional string withdrawType = 5;</code>
       */
      public com.google.protobuf.ByteString
          getWithdrawTypeBytes() {
        Object ref = withdrawType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          withdrawType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *提现类型    0  现金    1  汇款
       * </pre>
       *
       * <code>optional string withdrawType = 5;</code>
       */
      public Builder setWithdrawType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        withdrawType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *提现类型    0  现金    1  汇款
       * </pre>
       *
       * <code>optional string withdrawType = 5;</code>
       */
      public Builder clearWithdrawType() {
        
        withdrawType_ = getDefaultInstance().getWithdrawType();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *提现类型    0  现金    1  汇款
       * </pre>
       *
       * <code>optional string withdrawType = 5;</code>
       */
      public Builder setWithdrawTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        withdrawType_ = value;
        onChanged();
        return this;
      }

      private Object withdrawAccount_ = "";
      /**
       * <pre>
       *提现账号
       * </pre>
       *
       * <code>optional string withdrawAccount = 6;</code>
       */
      public String getWithdrawAccount() {
        Object ref = withdrawAccount_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          withdrawAccount_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *提现账号
       * </pre>
       *
       * <code>optional string withdrawAccount = 6;</code>
       */
      public com.google.protobuf.ByteString
          getWithdrawAccountBytes() {
        Object ref = withdrawAccount_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          withdrawAccount_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *提现账号
       * </pre>
       *
       * <code>optional string withdrawAccount = 6;</code>
       */
      public Builder setWithdrawAccount(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        withdrawAccount_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *提现账号
       * </pre>
       *
       * <code>optional string withdrawAccount = 6;</code>
       */
      public Builder clearWithdrawAccount() {
        
        withdrawAccount_ = getDefaultInstance().getWithdrawAccount();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *提现账号
       * </pre>
       *
       * <code>optional string withdrawAccount = 6;</code>
       */
      public Builder setWithdrawAccountBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        withdrawAccount_ = value;
        onChanged();
        return this;
      }

      private Object withdrawBank_ = "";
      /**
       * <pre>
       *开户行
       * </pre>
       *
       * <code>optional string withdrawBank = 7;</code>
       */
      public String getWithdrawBank() {
        Object ref = withdrawBank_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          withdrawBank_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *开户行
       * </pre>
       *
       * <code>optional string withdrawBank = 7;</code>
       */
      public com.google.protobuf.ByteString
          getWithdrawBankBytes() {
        Object ref = withdrawBank_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          withdrawBank_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *开户行
       * </pre>
       *
       * <code>optional string withdrawBank = 7;</code>
       */
      public Builder setWithdrawBank(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        withdrawBank_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *开户行
       * </pre>
       *
       * <code>optional string withdrawBank = 7;</code>
       */
      public Builder clearWithdrawBank() {
        
        withdrawBank_ = getDefaultInstance().getWithdrawBank();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *开户行
       * </pre>
       *
       * <code>optional string withdrawBank = 7;</code>
       */
      public Builder setWithdrawBankBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        withdrawBank_ = value;
        onChanged();
        return this;
      }

      private Object name_ = "";
      /**
       * <pre>
       *提现人
       * </pre>
       *
       * <code>optional string name = 8;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *提现人
       * </pre>
       *
       * <code>optional string name = 8;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *提现人
       * </pre>
       *
       * <code>optional string name = 8;</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *提现人
       * </pre>
       *
       * <code>optional string name = 8;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *提现人
       * </pre>
       *
       * <code>optional string name = 8;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private long id_ ;
      /**
       * <pre>
       *id
       * </pre>
       *
       * <code>optional int64 id = 9;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <pre>
       *id
       * </pre>
       *
       * <code>optional int64 id = 9;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *id
       * </pre>
       *
       * <code>optional int64 id = 9;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ApplyBikeInsuranceCashRequestMessage)
    }

    // @@protoc_insertion_point(class_scope:ApplyBikeInsuranceCashRequestMessage)
    private static final ApplyBikeInsuranceCashRequestMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ApplyBikeInsuranceCashRequestMessage();
    }

    public static ApplyBikeInsuranceCashRequestMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ApplyBikeInsuranceCashRequestMessage>
        PARSER = new com.google.protobuf.AbstractParser<ApplyBikeInsuranceCashRequestMessage>() {
      public ApplyBikeInsuranceCashRequestMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ApplyBikeInsuranceCashRequestMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ApplyBikeInsuranceCashRequestMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ApplyBikeInsuranceCashRequestMessage> getParserForType() {
      return PARSER;
    }

    public ApplyBikeInsuranceCashRequestMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ApplyBikeInsuranceCashRequestMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ApplyBikeInsuranceCashRequestMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n#ApplyBikeInsuranceCashRequest.proto\"\273\001" +
      "\n$ApplyBikeInsuranceCashRequestMessage\022\016" +
      "\n\006bikeId\030\001 \001(\003\022\023\n\013insuranceId\030\002 \001(\003\022\017\n\007s" +
      "ession\030\004 \001(\t\022\024\n\014withdrawType\030\005 \001(\t\022\027\n\017wi" +
      "thdrawAccount\030\006 \001(\t\022\024\n\014withdrawBank\030\007 \001(" +
      "\t\022\014\n\004name\030\010 \001(\t\022\n\n\002id\030\t \001(\003B=\n\034com.yzh.r" +
      "fidbike.app.requestB\035ApplyBikeInsuranceC" +
      "ashRequestb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ApplyBikeInsuranceCashRequestMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ApplyBikeInsuranceCashRequestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ApplyBikeInsuranceCashRequestMessage_descriptor,
        new String[] { "BikeId", "InsuranceId", "Session", "WithdrawType", "WithdrawAccount", "WithdrawBank", "Name", "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
