// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EditBikeFenceRequest.proto

package com.yzh.rfidbike.app.request;

public final class EditBikeFenceRequest {
  private EditBikeFenceRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EditBikeFenceRequestMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:EditBikeFenceRequestMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 操作类型      new   新增  ，edit   编辑  delete  删除
     * </pre>
     *
     * <code>optional .Type type = 1;</code>
     */
    int getTypeValue();
    /**
     * <pre>
     * 操作类型      new   新增  ，edit   编辑  delete  删除
     * </pre>
     *
     * <code>optional .Type type = 1;</code>
     */
    Types.Type getType();

    /**
     * <pre>
     *主键   编辑,修改时候传入
     * </pre>
     *
     * <code>optional int64 id = 2;</code>
     */
    long getId();

    /**
     * <code>optional int64 companyId = 3;</code>
     */
    long getCompanyId();

    /**
     * <code>optional int64 officeId = 4;</code>
     */
    long getOfficeId();

    /**
     * <code>optional int64 bikeId = 5;</code>
     */
    long getBikeId();

    /**
     * <pre>
     * 电子围栏名称
     * </pre>
     *
     * <code>optional string name = 6;</code>
     */
    String getName();
    /**
     * <pre>
     * 电子围栏名称
     * </pre>
     *
     * <code>optional string name = 6;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     *经度
     * </pre>
     *
     * <code>optional double lng = 7;</code>
     */
    double getLng();

    /**
     * <pre>
     *纬度
     * </pre>
     *
     * <code>optional double lat = 8;</code>
     */
    double getLat();

    /**
     * <pre>
     *围栏半径
     * </pre>
     *
     * <code>optional int32 radius = 9;</code>
     */
    int getRadius();

    /**
     * <pre>
     *是否设置入栏警告
     * </pre>
     *
     * <code>optional bool inAlert = 10;</code>
     */
    boolean getInAlert();

    /**
     * <pre>
     *是否设置出栏警告
     * </pre>
     *
     * <code>optional bool outAlert = 11;</code>
     */
    boolean getOutAlert();

    /**
     * <pre>
     *操作人session
     * </pre>
     *
     * <code>optional string session = 12;</code>
     */
    String getSession();
    /**
     * <pre>
     *操作人session
     * </pre>
     *
     * <code>optional string session = 12;</code>
     */
    com.google.protobuf.ByteString
        getSessionBytes();

    /**
     * <code>optional string remarks = 13;</code>
     */
    String getRemarks();
    /**
     * <code>optional string remarks = 13;</code>
     */
    com.google.protobuf.ByteString
        getRemarksBytes();
  }
  /**
   * <pre>
   *编辑自行车电子围栏请求消息
   * </pre>
   *
   * Protobuf type {@code EditBikeFenceRequestMessage}
   */
  public  static final class EditBikeFenceRequestMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:EditBikeFenceRequestMessage)
      EditBikeFenceRequestMessageOrBuilder {
    // Use EditBikeFenceRequestMessage.newBuilder() to construct.
    private EditBikeFenceRequestMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EditBikeFenceRequestMessage() {
      type_ = 0;
      id_ = 0L;
      companyId_ = 0L;
      officeId_ = 0L;
      bikeId_ = 0L;
      name_ = "";
      lng_ = 0D;
      lat_ = 0D;
      radius_ = 0;
      inAlert_ = false;
      outAlert_ = false;
      session_ = "";
      remarks_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private EditBikeFenceRequestMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 16: {

              id_ = input.readInt64();
              break;
            }
            case 24: {

              companyId_ = input.readInt64();
              break;
            }
            case 32: {

              officeId_ = input.readInt64();
              break;
            }
            case 40: {

              bikeId_ = input.readInt64();
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 57: {

              lng_ = input.readDouble();
              break;
            }
            case 65: {

              lat_ = input.readDouble();
              break;
            }
            case 72: {

              radius_ = input.readInt32();
              break;
            }
            case 80: {

              inAlert_ = input.readBool();
              break;
            }
            case 88: {

              outAlert_ = input.readBool();
              break;
            }
            case 98: {
              String s = input.readStringRequireUtf8();

              session_ = s;
              break;
            }
            case 106: {
              String s = input.readStringRequireUtf8();

              remarks_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EditBikeFenceRequest.internal_static_EditBikeFenceRequestMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EditBikeFenceRequest.internal_static_EditBikeFenceRequestMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              EditBikeFenceRequestMessage.class, Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <pre>
     * 操作类型      new   新增  ，edit   编辑  delete  删除
     * </pre>
     *
     * <code>optional .Type type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * 操作类型      new   新增  ，edit   编辑  delete  删除
     * </pre>
     *
     * <code>optional .Type type = 1;</code>
     */
    public Types.Type getType() {
      Types.Type result = Types.Type.valueOf(type_);
      return result == null ? Types.Type.UNRECOGNIZED : result;
    }

    public static final int ID_FIELD_NUMBER = 2;
    private long id_;
    /**
     * <pre>
     *主键   编辑,修改时候传入
     * </pre>
     *
     * <code>optional int64 id = 2;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int COMPANYID_FIELD_NUMBER = 3;
    private long companyId_;
    /**
     * <code>optional int64 companyId = 3;</code>
     */
    public long getCompanyId() {
      return companyId_;
    }

    public static final int OFFICEID_FIELD_NUMBER = 4;
    private long officeId_;
    /**
     * <code>optional int64 officeId = 4;</code>
     */
    public long getOfficeId() {
      return officeId_;
    }

    public static final int BIKEID_FIELD_NUMBER = 5;
    private long bikeId_;
    /**
     * <code>optional int64 bikeId = 5;</code>
     */
    public long getBikeId() {
      return bikeId_;
    }

    public static final int NAME_FIELD_NUMBER = 6;
    private volatile Object name_;
    /**
     * <pre>
     * 电子围栏名称
     * </pre>
     *
     * <code>optional string name = 6;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 电子围栏名称
     * </pre>
     *
     * <code>optional string name = 6;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LNG_FIELD_NUMBER = 7;
    private double lng_;
    /**
     * <pre>
     *经度
     * </pre>
     *
     * <code>optional double lng = 7;</code>
     */
    public double getLng() {
      return lng_;
    }

    public static final int LAT_FIELD_NUMBER = 8;
    private double lat_;
    /**
     * <pre>
     *纬度
     * </pre>
     *
     * <code>optional double lat = 8;</code>
     */
    public double getLat() {
      return lat_;
    }

    public static final int RADIUS_FIELD_NUMBER = 9;
    private int radius_;
    /**
     * <pre>
     *围栏半径
     * </pre>
     *
     * <code>optional int32 radius = 9;</code>
     */
    public int getRadius() {
      return radius_;
    }

    public static final int INALERT_FIELD_NUMBER = 10;
    private boolean inAlert_;
    /**
     * <pre>
     *是否设置入栏警告
     * </pre>
     *
     * <code>optional bool inAlert = 10;</code>
     */
    public boolean getInAlert() {
      return inAlert_;
    }

    public static final int OUTALERT_FIELD_NUMBER = 11;
    private boolean outAlert_;
    /**
     * <pre>
     *是否设置出栏警告
     * </pre>
     *
     * <code>optional bool outAlert = 11;</code>
     */
    public boolean getOutAlert() {
      return outAlert_;
    }

    public static final int SESSION_FIELD_NUMBER = 12;
    private volatile Object session_;
    /**
     * <pre>
     *操作人session
     * </pre>
     *
     * <code>optional string session = 12;</code>
     */
    public String getSession() {
      Object ref = session_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        session_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *操作人session
     * </pre>
     *
     * <code>optional string session = 12;</code>
     */
    public com.google.protobuf.ByteString
        getSessionBytes() {
      Object ref = session_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        session_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REMARKS_FIELD_NUMBER = 13;
    private volatile Object remarks_;
    /**
     * <code>optional string remarks = 13;</code>
     */
    public String getRemarks() {
      Object ref = remarks_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        remarks_ = s;
        return s;
      }
    }
    /**
     * <code>optional string remarks = 13;</code>
     */
    public com.google.protobuf.ByteString
        getRemarksBytes() {
      Object ref = remarks_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        remarks_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != Types.Type.NEW.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (id_ != 0L) {
        output.writeInt64(2, id_);
      }
      if (companyId_ != 0L) {
        output.writeInt64(3, companyId_);
      }
      if (officeId_ != 0L) {
        output.writeInt64(4, officeId_);
      }
      if (bikeId_ != 0L) {
        output.writeInt64(5, bikeId_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, name_);
      }
      if (lng_ != 0D) {
        output.writeDouble(7, lng_);
      }
      if (lat_ != 0D) {
        output.writeDouble(8, lat_);
      }
      if (radius_ != 0) {
        output.writeInt32(9, radius_);
      }
      if (inAlert_ != false) {
        output.writeBool(10, inAlert_);
      }
      if (outAlert_ != false) {
        output.writeBool(11, outAlert_);
      }
      if (!getSessionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, session_);
      }
      if (!getRemarksBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, remarks_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != Types.Type.NEW.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, id_);
      }
      if (companyId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, companyId_);
      }
      if (officeId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, officeId_);
      }
      if (bikeId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, bikeId_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, name_);
      }
      if (lng_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, lng_);
      }
      if (lat_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(8, lat_);
      }
      if (radius_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, radius_);
      }
      if (inAlert_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(10, inAlert_);
      }
      if (outAlert_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(11, outAlert_);
      }
      if (!getSessionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, session_);
      }
      if (!getRemarksBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, remarks_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof EditBikeFenceRequestMessage)) {
        return super.equals(obj);
      }
      EditBikeFenceRequestMessage other = (EditBikeFenceRequestMessage) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && (getId()
          == other.getId());
      result = result && (getCompanyId()
          == other.getCompanyId());
      result = result && (getOfficeId()
          == other.getOfficeId());
      result = result && (getBikeId()
          == other.getBikeId());
      result = result && getName()
          .equals(other.getName());
      result = result && (
          Double.doubleToLongBits(getLng())
          == Double.doubleToLongBits(
              other.getLng()));
      result = result && (
          Double.doubleToLongBits(getLat())
          == Double.doubleToLongBits(
              other.getLat()));
      result = result && (getRadius()
          == other.getRadius());
      result = result && (getInAlert()
          == other.getInAlert());
      result = result && (getOutAlert()
          == other.getOutAlert());
      result = result && getSession()
          .equals(other.getSession());
      result = result && getRemarks()
          .equals(other.getRemarks());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + COMPANYID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCompanyId());
      hash = (37 * hash) + OFFICEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getOfficeId());
      hash = (37 * hash) + BIKEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBikeId());
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + LNG_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getLng()));
      hash = (37 * hash) + LAT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getLat()));
      hash = (37 * hash) + RADIUS_FIELD_NUMBER;
      hash = (53 * hash) + getRadius();
      hash = (37 * hash) + INALERT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getInAlert());
      hash = (37 * hash) + OUTALERT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getOutAlert());
      hash = (37 * hash) + SESSION_FIELD_NUMBER;
      hash = (53 * hash) + getSession().hashCode();
      hash = (37 * hash) + REMARKS_FIELD_NUMBER;
      hash = (53 * hash) + getRemarks().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static EditBikeFenceRequestMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EditBikeFenceRequestMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EditBikeFenceRequestMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EditBikeFenceRequestMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EditBikeFenceRequestMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static EditBikeFenceRequestMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static EditBikeFenceRequestMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static EditBikeFenceRequestMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static EditBikeFenceRequestMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static EditBikeFenceRequestMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(EditBikeFenceRequestMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *编辑自行车电子围栏请求消息
     * </pre>
     *
     * Protobuf type {@code EditBikeFenceRequestMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:EditBikeFenceRequestMessage)
        EditBikeFenceRequestMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return EditBikeFenceRequest.internal_static_EditBikeFenceRequestMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return EditBikeFenceRequest.internal_static_EditBikeFenceRequestMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                EditBikeFenceRequestMessage.class, Builder.class);
      }

      // Construct using com.yzh.rfidbike.app.request.EditBikeFenceRequest.EditBikeFenceRequestMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        id_ = 0L;

        companyId_ = 0L;

        officeId_ = 0L;

        bikeId_ = 0L;

        name_ = "";

        lng_ = 0D;

        lat_ = 0D;

        radius_ = 0;

        inAlert_ = false;

        outAlert_ = false;

        session_ = "";

        remarks_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return EditBikeFenceRequest.internal_static_EditBikeFenceRequestMessage_descriptor;
      }

      public EditBikeFenceRequestMessage getDefaultInstanceForType() {
        return EditBikeFenceRequestMessage.getDefaultInstance();
      }

      public EditBikeFenceRequestMessage build() {
        EditBikeFenceRequestMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public EditBikeFenceRequestMessage buildPartial() {
        EditBikeFenceRequestMessage result = new EditBikeFenceRequestMessage(this);
        result.type_ = type_;
        result.id_ = id_;
        result.companyId_ = companyId_;
        result.officeId_ = officeId_;
        result.bikeId_ = bikeId_;
        result.name_ = name_;
        result.lng_ = lng_;
        result.lat_ = lat_;
        result.radius_ = radius_;
        result.inAlert_ = inAlert_;
        result.outAlert_ = outAlert_;
        result.session_ = session_;
        result.remarks_ = remarks_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof EditBikeFenceRequestMessage) {
          return mergeFrom((EditBikeFenceRequestMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(EditBikeFenceRequestMessage other) {
        if (other == EditBikeFenceRequestMessage.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.getCompanyId() != 0L) {
          setCompanyId(other.getCompanyId());
        }
        if (other.getOfficeId() != 0L) {
          setOfficeId(other.getOfficeId());
        }
        if (other.getBikeId() != 0L) {
          setBikeId(other.getBikeId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getLng() != 0D) {
          setLng(other.getLng());
        }
        if (other.getLat() != 0D) {
          setLat(other.getLat());
        }
        if (other.getRadius() != 0) {
          setRadius(other.getRadius());
        }
        if (other.getInAlert() != false) {
          setInAlert(other.getInAlert());
        }
        if (other.getOutAlert() != false) {
          setOutAlert(other.getOutAlert());
        }
        if (!other.getSession().isEmpty()) {
          session_ = other.session_;
          onChanged();
        }
        if (!other.getRemarks().isEmpty()) {
          remarks_ = other.remarks_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        EditBikeFenceRequestMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (EditBikeFenceRequestMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <pre>
       * 操作类型      new   新增  ，edit   编辑  delete  删除
       * </pre>
       *
       * <code>optional .Type type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <pre>
       * 操作类型      new   新增  ，edit   编辑  delete  删除
       * </pre>
       *
       * <code>optional .Type type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 操作类型      new   新增  ，edit   编辑  delete  删除
       * </pre>
       *
       * <code>optional .Type type = 1;</code>
       */
      public Types.Type getType() {
        Types.Type result = Types.Type.valueOf(type_);
        return result == null ? Types.Type.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 操作类型      new   新增  ，edit   编辑  delete  删除
       * </pre>
       *
       * <code>optional .Type type = 1;</code>
       */
      public Builder setType(Types.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 操作类型      new   新增  ，edit   编辑  delete  删除
       * </pre>
       *
       * <code>optional .Type type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private long id_ ;
      /**
       * <pre>
       *主键   编辑,修改时候传入
       * </pre>
       *
       * <code>optional int64 id = 2;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <pre>
       *主键   编辑,修改时候传入
       * </pre>
       *
       * <code>optional int64 id = 2;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *主键   编辑,修改时候传入
       * </pre>
       *
       * <code>optional int64 id = 2;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private long companyId_ ;
      /**
       * <code>optional int64 companyId = 3;</code>
       */
      public long getCompanyId() {
        return companyId_;
      }
      /**
       * <code>optional int64 companyId = 3;</code>
       */
      public Builder setCompanyId(long value) {
        
        companyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 companyId = 3;</code>
       */
      public Builder clearCompanyId() {
        
        companyId_ = 0L;
        onChanged();
        return this;
      }

      private long officeId_ ;
      /**
       * <code>optional int64 officeId = 4;</code>
       */
      public long getOfficeId() {
        return officeId_;
      }
      /**
       * <code>optional int64 officeId = 4;</code>
       */
      public Builder setOfficeId(long value) {
        
        officeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 officeId = 4;</code>
       */
      public Builder clearOfficeId() {
        
        officeId_ = 0L;
        onChanged();
        return this;
      }

      private long bikeId_ ;
      /**
       * <code>optional int64 bikeId = 5;</code>
       */
      public long getBikeId() {
        return bikeId_;
      }
      /**
       * <code>optional int64 bikeId = 5;</code>
       */
      public Builder setBikeId(long value) {
        
        bikeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 bikeId = 5;</code>
       */
      public Builder clearBikeId() {
        
        bikeId_ = 0L;
        onChanged();
        return this;
      }

      private Object name_ = "";
      /**
       * <pre>
       * 电子围栏名称
       * </pre>
       *
       * <code>optional string name = 6;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 电子围栏名称
       * </pre>
       *
       * <code>optional string name = 6;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 电子围栏名称
       * </pre>
       *
       * <code>optional string name = 6;</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 电子围栏名称
       * </pre>
       *
       * <code>optional string name = 6;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 电子围栏名称
       * </pre>
       *
       * <code>optional string name = 6;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private double lng_ ;
      /**
       * <pre>
       *经度
       * </pre>
       *
       * <code>optional double lng = 7;</code>
       */
      public double getLng() {
        return lng_;
      }
      /**
       * <pre>
       *经度
       * </pre>
       *
       * <code>optional double lng = 7;</code>
       */
      public Builder setLng(double value) {
        
        lng_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *经度
       * </pre>
       *
       * <code>optional double lng = 7;</code>
       */
      public Builder clearLng() {
        
        lng_ = 0D;
        onChanged();
        return this;
      }

      private double lat_ ;
      /**
       * <pre>
       *纬度
       * </pre>
       *
       * <code>optional double lat = 8;</code>
       */
      public double getLat() {
        return lat_;
      }
      /**
       * <pre>
       *纬度
       * </pre>
       *
       * <code>optional double lat = 8;</code>
       */
      public Builder setLat(double value) {
        
        lat_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *纬度
       * </pre>
       *
       * <code>optional double lat = 8;</code>
       */
      public Builder clearLat() {
        
        lat_ = 0D;
        onChanged();
        return this;
      }

      private int radius_ ;
      /**
       * <pre>
       *围栏半径
       * </pre>
       *
       * <code>optional int32 radius = 9;</code>
       */
      public int getRadius() {
        return radius_;
      }
      /**
       * <pre>
       *围栏半径
       * </pre>
       *
       * <code>optional int32 radius = 9;</code>
       */
      public Builder setRadius(int value) {
        
        radius_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *围栏半径
       * </pre>
       *
       * <code>optional int32 radius = 9;</code>
       */
      public Builder clearRadius() {
        
        radius_ = 0;
        onChanged();
        return this;
      }

      private boolean inAlert_ ;
      /**
       * <pre>
       *是否设置入栏警告
       * </pre>
       *
       * <code>optional bool inAlert = 10;</code>
       */
      public boolean getInAlert() {
        return inAlert_;
      }
      /**
       * <pre>
       *是否设置入栏警告
       * </pre>
       *
       * <code>optional bool inAlert = 10;</code>
       */
      public Builder setInAlert(boolean value) {
        
        inAlert_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否设置入栏警告
       * </pre>
       *
       * <code>optional bool inAlert = 10;</code>
       */
      public Builder clearInAlert() {
        
        inAlert_ = false;
        onChanged();
        return this;
      }

      private boolean outAlert_ ;
      /**
       * <pre>
       *是否设置出栏警告
       * </pre>
       *
       * <code>optional bool outAlert = 11;</code>
       */
      public boolean getOutAlert() {
        return outAlert_;
      }
      /**
       * <pre>
       *是否设置出栏警告
       * </pre>
       *
       * <code>optional bool outAlert = 11;</code>
       */
      public Builder setOutAlert(boolean value) {
        
        outAlert_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否设置出栏警告
       * </pre>
       *
       * <code>optional bool outAlert = 11;</code>
       */
      public Builder clearOutAlert() {
        
        outAlert_ = false;
        onChanged();
        return this;
      }

      private Object session_ = "";
      /**
       * <pre>
       *操作人session
       * </pre>
       *
       * <code>optional string session = 12;</code>
       */
      public String getSession() {
        Object ref = session_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          session_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *操作人session
       * </pre>
       *
       * <code>optional string session = 12;</code>
       */
      public com.google.protobuf.ByteString
          getSessionBytes() {
        Object ref = session_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          session_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *操作人session
       * </pre>
       *
       * <code>optional string session = 12;</code>
       */
      public Builder setSession(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        session_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *操作人session
       * </pre>
       *
       * <code>optional string session = 12;</code>
       */
      public Builder clearSession() {
        
        session_ = getDefaultInstance().getSession();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *操作人session
       * </pre>
       *
       * <code>optional string session = 12;</code>
       */
      public Builder setSessionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        session_ = value;
        onChanged();
        return this;
      }

      private Object remarks_ = "";
      /**
       * <code>optional string remarks = 13;</code>
       */
      public String getRemarks() {
        Object ref = remarks_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          remarks_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string remarks = 13;</code>
       */
      public com.google.protobuf.ByteString
          getRemarksBytes() {
        Object ref = remarks_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          remarks_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string remarks = 13;</code>
       */
      public Builder setRemarks(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        remarks_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string remarks = 13;</code>
       */
      public Builder clearRemarks() {
        
        remarks_ = getDefaultInstance().getRemarks();
        onChanged();
        return this;
      }
      /**
       * <code>optional string remarks = 13;</code>
       */
      public Builder setRemarksBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        remarks_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:EditBikeFenceRequestMessage)
    }

    // @@protoc_insertion_point(class_scope:EditBikeFenceRequestMessage)
    private static final EditBikeFenceRequestMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new EditBikeFenceRequestMessage();
    }

    public static EditBikeFenceRequestMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EditBikeFenceRequestMessage>
        PARSER = new com.google.protobuf.AbstractParser<EditBikeFenceRequestMessage>() {
      public EditBikeFenceRequestMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new EditBikeFenceRequestMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EditBikeFenceRequestMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<EditBikeFenceRequestMessage> getParserForType() {
      return PARSER;
    }

    public EditBikeFenceRequestMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EditBikeFenceRequestMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EditBikeFenceRequestMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\032EditBikeFenceRequest.proto\032\013Types.prot" +
      "o\"\360\001\n\033EditBikeFenceRequestMessage\022\023\n\004typ" +
      "e\030\001 \001(\0162\005.Type\022\n\n\002id\030\002 \001(\003\022\021\n\tcompanyId\030" +
      "\003 \001(\003\022\020\n\010officeId\030\004 \001(\003\022\016\n\006bikeId\030\005 \001(\003\022" +
      "\014\n\004name\030\006 \001(\t\022\013\n\003lng\030\007 \001(\001\022\013\n\003lat\030\010 \001(\001\022" +
      "\016\n\006radius\030\t \001(\005\022\017\n\007inAlert\030\n \001(\010\022\020\n\010outA" +
      "lert\030\013 \001(\010\022\017\n\007session\030\014 \001(\t\022\017\n\007remarks\030\r" +
      " \001(\tB4\n\034com.yzh.rfidbike.app.requestB\024Ed" +
      "itBikeFenceRequestb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Types.getDescriptor(),
        }, assigner);
    internal_static_EditBikeFenceRequestMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_EditBikeFenceRequestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EditBikeFenceRequestMessage_descriptor,
        new String[] { "Type", "Id", "CompanyId", "OfficeId", "BikeId", "Name", "Lng", "Lat", "Radius", "InAlert", "OutAlert", "Session", "Remarks", });
    Types.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
