// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetBikeCurLocationRequest.proto

package com.yzh.rfidbike.app.request;

public final class GetBikeCurLocationRequest {
  private GetBikeCurLocationRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetBikeCurLocationRequestMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetBikeCurLocationRequestMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string session = 1;</code>
     */
    String getSession();
    /**
     * <code>optional string session = 1;</code>
     */
    com.google.protobuf.ByteString
        getSessionBytes();

    /**
     * <code>repeated int64 bikeId = 2;</code>
     */
    java.util.List<Long> getBikeIdList();
    /**
     * <code>repeated int64 bikeId = 2;</code>
     */
    int getBikeIdCount();
    /**
     * <code>repeated int64 bikeId = 2;</code>
     */
    long getBikeId(int index);
  }
  /**
   * Protobuf type {@code GetBikeCurLocationRequestMessage}
   */
  public  static final class GetBikeCurLocationRequestMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetBikeCurLocationRequestMessage)
      GetBikeCurLocationRequestMessageOrBuilder {
    // Use GetBikeCurLocationRequestMessage.newBuilder() to construct.
    private GetBikeCurLocationRequestMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetBikeCurLocationRequestMessage() {
      session_ = "";
      bikeId_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetBikeCurLocationRequestMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              session_ = s;
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                bikeId_ = new java.util.ArrayList<Long>();
                mutable_bitField0_ |= 0x00000002;
              }
              bikeId_.add(input.readInt64());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                bikeId_ = new java.util.ArrayList<Long>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                bikeId_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          bikeId_ = java.util.Collections.unmodifiableList(bikeId_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GetBikeCurLocationRequest.internal_static_GetBikeCurLocationRequestMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GetBikeCurLocationRequest.internal_static_GetBikeCurLocationRequestMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GetBikeCurLocationRequestMessage.class, Builder.class);
    }

    private int bitField0_;
    public static final int SESSION_FIELD_NUMBER = 1;
    private volatile Object session_;
    /**
     * <code>optional string session = 1;</code>
     */
    public String getSession() {
      Object ref = session_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        session_ = s;
        return s;
      }
    }
    /**
     * <code>optional string session = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSessionBytes() {
      Object ref = session_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        session_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BIKEID_FIELD_NUMBER = 2;
    private java.util.List<Long> bikeId_;
    /**
     * <code>repeated int64 bikeId = 2;</code>
     */
    public java.util.List<Long>
        getBikeIdList() {
      return bikeId_;
    }
    /**
     * <code>repeated int64 bikeId = 2;</code>
     */
    public int getBikeIdCount() {
      return bikeId_.size();
    }
    /**
     * <code>repeated int64 bikeId = 2;</code>
     */
    public long getBikeId(int index) {
      return bikeId_.get(index);
    }
    private int bikeIdMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (!getSessionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, session_);
      }
      if (getBikeIdList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(bikeIdMemoizedSerializedSize);
      }
      for (int i = 0; i < bikeId_.size(); i++) {
        output.writeInt64NoTag(bikeId_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSessionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, session_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < bikeId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(bikeId_.get(i));
        }
        size += dataSize;
        if (!getBikeIdList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        bikeIdMemoizedSerializedSize = dataSize;
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GetBikeCurLocationRequestMessage)) {
        return super.equals(obj);
      }
      GetBikeCurLocationRequestMessage other = (GetBikeCurLocationRequestMessage) obj;

      boolean result = true;
      result = result && getSession()
          .equals(other.getSession());
      result = result && getBikeIdList()
          .equals(other.getBikeIdList());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + SESSION_FIELD_NUMBER;
      hash = (53 * hash) + getSession().hashCode();
      if (getBikeIdCount() > 0) {
        hash = (37 * hash) + BIKEID_FIELD_NUMBER;
        hash = (53 * hash) + getBikeIdList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GetBikeCurLocationRequestMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GetBikeCurLocationRequestMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GetBikeCurLocationRequestMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GetBikeCurLocationRequestMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GetBikeCurLocationRequestMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GetBikeCurLocationRequestMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GetBikeCurLocationRequestMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GetBikeCurLocationRequestMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GetBikeCurLocationRequestMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GetBikeCurLocationRequestMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GetBikeCurLocationRequestMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetBikeCurLocationRequestMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetBikeCurLocationRequestMessage)
        GetBikeCurLocationRequestMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GetBikeCurLocationRequest.internal_static_GetBikeCurLocationRequestMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GetBikeCurLocationRequest.internal_static_GetBikeCurLocationRequestMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GetBikeCurLocationRequestMessage.class, Builder.class);
      }

      // Construct using com.yzh.rfidbike.app.request.GetBikeCurLocationRequest.GetBikeCurLocationRequestMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        session_ = "";

        bikeId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GetBikeCurLocationRequest.internal_static_GetBikeCurLocationRequestMessage_descriptor;
      }

      public GetBikeCurLocationRequestMessage getDefaultInstanceForType() {
        return GetBikeCurLocationRequestMessage.getDefaultInstance();
      }

      public GetBikeCurLocationRequestMessage build() {
        GetBikeCurLocationRequestMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public GetBikeCurLocationRequestMessage buildPartial() {
        GetBikeCurLocationRequestMessage result = new GetBikeCurLocationRequestMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.session_ = session_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          bikeId_ = java.util.Collections.unmodifiableList(bikeId_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.bikeId_ = bikeId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GetBikeCurLocationRequestMessage) {
          return mergeFrom((GetBikeCurLocationRequestMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GetBikeCurLocationRequestMessage other) {
        if (other == GetBikeCurLocationRequestMessage.getDefaultInstance()) return this;
        if (!other.getSession().isEmpty()) {
          session_ = other.session_;
          onChanged();
        }
        if (!other.bikeId_.isEmpty()) {
          if (bikeId_.isEmpty()) {
            bikeId_ = other.bikeId_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureBikeIdIsMutable();
            bikeId_.addAll(other.bikeId_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GetBikeCurLocationRequestMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GetBikeCurLocationRequestMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object session_ = "";
      /**
       * <code>optional string session = 1;</code>
       */
      public String getSession() {
        Object ref = session_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          session_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string session = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSessionBytes() {
        Object ref = session_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          session_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string session = 1;</code>
       */
      public Builder setSession(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        session_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string session = 1;</code>
       */
      public Builder clearSession() {
        
        session_ = getDefaultInstance().getSession();
        onChanged();
        return this;
      }
      /**
       * <code>optional string session = 1;</code>
       */
      public Builder setSessionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        session_ = value;
        onChanged();
        return this;
      }

      private java.util.List<Long> bikeId_ = java.util.Collections.emptyList();
      private void ensureBikeIdIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          bikeId_ = new java.util.ArrayList<Long>(bikeId_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int64 bikeId = 2;</code>
       */
      public java.util.List<Long>
          getBikeIdList() {
        return java.util.Collections.unmodifiableList(bikeId_);
      }
      /**
       * <code>repeated int64 bikeId = 2;</code>
       */
      public int getBikeIdCount() {
        return bikeId_.size();
      }
      /**
       * <code>repeated int64 bikeId = 2;</code>
       */
      public long getBikeId(int index) {
        return bikeId_.get(index);
      }
      /**
       * <code>repeated int64 bikeId = 2;</code>
       */
      public Builder setBikeId(
          int index, long value) {
        ensureBikeIdIsMutable();
        bikeId_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 bikeId = 2;</code>
       */
      public Builder addBikeId(long value) {
        ensureBikeIdIsMutable();
        bikeId_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 bikeId = 2;</code>
       */
      public Builder addAllBikeId(
          Iterable<? extends Long> values) {
        ensureBikeIdIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, bikeId_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 bikeId = 2;</code>
       */
      public Builder clearBikeId() {
        bikeId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:GetBikeCurLocationRequestMessage)
    }

    // @@protoc_insertion_point(class_scope:GetBikeCurLocationRequestMessage)
    private static final GetBikeCurLocationRequestMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GetBikeCurLocationRequestMessage();
    }

    public static GetBikeCurLocationRequestMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetBikeCurLocationRequestMessage>
        PARSER = new com.google.protobuf.AbstractParser<GetBikeCurLocationRequestMessage>() {
      public GetBikeCurLocationRequestMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetBikeCurLocationRequestMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetBikeCurLocationRequestMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<GetBikeCurLocationRequestMessage> getParserForType() {
      return PARSER;
    }

    public GetBikeCurLocationRequestMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetBikeCurLocationRequestMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetBikeCurLocationRequestMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\037GetBikeCurLocationRequest.proto\"C\n Get" +
      "BikeCurLocationRequestMessage\022\017\n\007session" +
      "\030\001 \001(\t\022\016\n\006bikeId\030\002 \003(\003B9\n\034com.yzh.rfidbi" +
      "ke.app.requestB\031GetBikeCurLocationReques" +
      "tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_GetBikeCurLocationRequestMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetBikeCurLocationRequestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetBikeCurLocationRequestMessage_descriptor,
        new String[] { "Session", "BikeId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
